### ISSUE TITLE
Accessing the Auth0 page directly does not open the login popup

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/tc-auth-lib#10]
Access the Auth0 page directly.
actual: Login popup not displayed
expected: Accessing the Auth0 page directly, must open the login popup and redirect to topcoder home page after login
https://accounts-auth0.topcoder-dev.com/
https://github.com/topcoder-platform/community-app/issues/4956

**Comment by SathyaJayabal** [comment]
https://github.com/topcoder-platform/community-app/issues/4956#issuecomment-695921512

**Comment by sachin-maheshwari** [comment]
Need to remove the current message.

**Comment by sachin-maheshwari** [comment]
message already updated. @SathyaJayabal please verify and close this issue.

**Comment by sandhiyakavi** [comment]
@sachin-maheshwari Is the following  the expected message?

![image](https://user-images.githubusercontent.com/55895538/102575864-8b3d7700-4137-11eb-9bac-a5065758e722.png)

**Comment by sachin-maheshwari** [comment]
Yes, i think user will get the flow once click on the "click here" and reach to the main site and from there he/she can go accordingly.

**Comment by sandhiyakavi** [comment]
Working as expected. Closing the issue
