### ISSUE TITLE
Terms and Privacy Policy Links

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/tc-auth-lib#100]
On the registration page, there is a statement at the bottom that says "By signing up, you agree to our terms...".

Both the terms and privacy policy should be linked to the pages on the site.

https://www.topcoder.com/policy/privacy-policy
https://www.topcoder.com/policy/terms-and-conditions

**Comment by ajefts** [comment]
fyi @mtwomey @sachin-maheshwari

**Comment by sachin-maheshwari** [comment]
sure. I'll add this.

**Comment by sachin-maheshwari** [comment]
done. @ajefts please verify.
