### ISSUE TITLE
Wrong login URL for online review

### ISSUE THREAD

**Issue by ajaysaini9782** [topcoder-platform/tc-auth-lib#102]
When I click the Login link on Online Review, it redirects to the following which is not a valid URL:

https//accounts-auth0.topcoder.com?retUrl=https://software.topcoder.com/review

**Comment by ajaysaini9782** [comment]
Issue reported by copilot Wendell

**Comment by sachin-maheshwari** [comment]
@ajaysaini9782 what'll be corrected/expected URL ? please share.

**Comment by ajaysaini9782** [comment]
@sachin-maheshwari 
with colons
https://accounts-auth0.topcoder.com?retUrl=https://software.topcoder.com/review

**Comment by sachin-maheshwari** [comment]
@ajaysaini9782 Thanks!. Please share screen or link to reach at login button for online review.

**Comment by ajaysaini9782** [comment]
@sachin-maheshwari 
I have forwarded your query to Wendell. He will share the details.

**Comment by huangqun** [comment]
Please check https://take.ms/qYpRT

Visit link https://software.topcoder.com/review/actions/ListProjects?scope=all and then click on the Login link on top right corner.

**Comment by sachin-maheshwari** [comment]
@huangqun i really appreciate it. Thankyou!. i'll fix this.

**Comment by sachin-maheshwari** [comment]
fixed.
