### ISSUE TITLE
User is logged out automatically after 5 minutes from vanilla Forums when logging from mobile devices

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-auth-lib#103]
**Steps**

- Log into Forums from https://vanilla.topcoder-dev.com/ from a mobile device(Andoid/iPhone)
- Keep the app idling for 5 minutes
- Tap on any linked text

User has been signed out, and redirect to auth login page and sign in again

The below video was taken after 5 mins of idle time

[OMRG6954.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5686957/OMRG6954.zip)

Device: iPhone 6S
OS: 13.7
Browser: Safari

Device: Pixel XL
OS: Android 10
Browser: Chrome

**Comment by sachin-maheshwari** [comment]
@sdgun same time, what about other apps (connect, WM, community etc) ? that are working fine ?

**Comment by sachin-maheshwari** [comment]
@sdgun as checked it is working fine for me on my Android mobile.

**Comment by sachin-maheshwari** [comment]
@lakshmiathreya there is no response from your team.
