### ISSUE TITLE
broken URL issue - for non logged-in user 

### ISSUE THREAD

**Issue by sachin-maheshwari** [topcoder-platform/tc-auth-lib#108]
After registering any challenge, we generally get the mail like below, where forum and OR link are available.

Hi <handle>,

Congratulations! You are now registered for [Dev][F2F][Challenge2-Dec10] Challenge.

You now have access to the challenge discussion forum ( https://apps.topcoder.com/forums/?module=Category&categoryID=131140 ), which may have important information or documentation(see the Design Phase Documents thread) about the challenge. It is also the place to ask questions regarding the challenge. Please post your questions at any time and the challenge holder will respond within 24 hours. Any questions asked within a few hours of the submission deadline may not be answered in time, so get your questions in early!

The deadline for submitting a solution is Dec 28, 2021 05:00 EST. Please upload your submission here: https://www.topcoder.com/challenges/30157201/submit/. If you encounter any problems, please contact us at support@topcoder.com. All late submissions will be ignored.

Additional tasks for this challenge can be accessed in Online Review. This is where you can unregister, contact a manager, view your review scorecard, submit appeals and final fixes, and other important tasks. https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30157201

Need more information about competing? Visit the Help Center at http://help.topcoder.com.

Do you have questions or technical problems? Please contact support@topcoder.com.

Good luck!
The topcoder Team

**Comment by lakshmiathreya** [comment]
@SathyaJayabal @sandhiyakavi can you review this in Dev pls?

**Comment by sandhiyakavi** [comment]
Verified with below url. The url is redirecting to auth0 Login page if not logged in.

https://apps.topcoder-dev.com/forums/?module=Category&categoryID=12345
https://software.topcoder-dev.com/review/actions/ViewProjectDetails?pid=30057927


https://user-images.githubusercontent.com/55895538/103973651-409da080-51b3-11eb-8ff9-1b11b9d8cac0.mp4

**Comment by sandhiyakavi** [comment]
@sachin-maheshwari Tested in Prod Environment for various tracks. Both Forum and OR URL's are directing correctly to the Auth0 login page.

**Comment by sandhiyakavi** [comment]
Verified the above issue in Dev Env with below URL's,

https://apps.topcoder-dev.com/forums/?module=Category&categoryID=12345
https://software.topcoder-dev.com/review/actions/ViewProjectDetails?pid=30057927

Forum URL is directing to the appropriate page after login. 
OR URL is directing to common page https://software.topcoder-dev.com/review/actions/ListProjects


https://user-images.githubusercontent.com/55895538/104000448-97ba6a00-51e1-11eb-9a74-d4158b4379b2.mp4

**Comment by sandhiyakavi** [comment]
@sachin-maheshwari The Forums topics and details are not getting displayed.

![image](https://user-images.githubusercontent.com/55895538/104429003-7a621300-55c8-11eb-9003-41538eb2896b.png)

Same Forum page if opened in already logged in Window.

<img width="960" alt="direct_forum_url" src="https://user-images.githubusercontent.com/55895538/104428830-44249380-55c8-11eb-95c0-0217da5c59cf.png">


OR page displaying  https://software.topcoder.com/review/actions/ListProjects

<img width="959" alt="OR_url" src="https://user-images.githubusercontent.com/55895538/104428923-628a8f00-55c8-11eb-92f7-e11341faf0e0.png">


https://user-images.githubusercontent.com/55895538/104429231-bbf2be00-55c8-11eb-8e4d-033b4f778ea5.mp4

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi as already discussed, this fix is not applicable to OR (that is existing OR issue).
<img width="1388" alt="Screenshot 2021-01-13 at 2 32 23 PM" src="https://user-images.githubusercontent.com/6467888/104429983-2ea17080-55ac-11eb-8c38-56d8747c47ae.png">

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi  Now it is working for me, looks like some intermittent issue at legacy forum app. 
<img width="1674" alt="Screenshot 2021-01-13 at 4 11 25 PM" src="https://user-images.githubusercontent.com/6467888/104442572-42080800-55bb-11eb-9934-4a4b0fff7905.png">

**Comment by sandhiyakavi** [comment]
Verified in Prod.Working as expected.


https://user-images.githubusercontent.com/55895538/104444392-1137cb00-55db-11eb-8e74-3e0588cd1625.mp4
