### ISSUE TITLE
Console error on all pages

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/tc-auth-lib#11]
The following console error on all pages
<img width="1440" alt="Screenshot 2020-09-18 at 5 28 09 PM" src="https://user-images.githubusercontent.com/58783823/93595132-cfa06600-f9d4-11ea-8007-07812b9de3ba.png">

Note: error only for `http`, works for `https`

**Comment by sachin-maheshwari** [comment]
@SathyaJayabal we are assuming you reach to "http" by typing on browser directly. correct ? otherwise no apps having link which is directly pointing to "http".

**Comment by sachin-maheshwari** [comment]
@mtwomey as discussed we need to fix this "http" from infra side. I need "https" for frontend auth0 sdk.

**Comment by mtwomey** [comment]
I think this is fixed now, but I also can not reproduce it (even before adding an extra http -> https redifect.

**Comment by drasticdpk** [comment]
Currently there is no such error, closing it. If anything we can re-open it. 
![image](https://user-images.githubusercontent.com/25297859/124269008-0dccd780-db5a-11eb-8b42-c5efc003671c.png)
