### ISSUE TITLE
User unable to sign NDA in dev env

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/tc-auth-lib#112]
User unable to sign NDA in dev env
test url:
https://www.topcoder-dev.com/challenges/terms/detail/e5811a7b-43d1-407a-a064-69e5015b4900

<img width="1440" alt="Screenshot 2021-03-01 at 12 33 20 PM" src="https://user-images.githubusercontent.com/58783823/109463041-65fbac00-7a8a-11eb-811f-36e1c23ca319.png">

@sachin-maheshwari , can you please take a look at this?

**Comment by lakshmiathreya** [comment]
cc @drasticdpk @vikasrohit @rootelement ... this is related to https://github.com/topcoder-platform/work-manager/issues/1089

**Comment by sachin-maheshwari** [comment]
@SathyaJayabal that is not related to auth0, this should be related to "term" service. Please connect with Community team. 
<img width="1393" alt="Screenshot 2021-03-01 at 4 38 19 PM" src="https://user-images.githubusercontent.com/6467888/109489215-8b011680-7aac-11eb-9334-0e7e6f102053.png">

**Comment by rootelement** [comment]
Terms in dev didn't have any body text. I added some and now see them in the URL:
https://www.topcoder-dev.com/challenges/terms/detail/317cd8f9-d66c-4f2a-8774-63c612d99cd4 

Please try again. I was able to sign with a basic user who hasn't signed them.

**Comment by SathyaJayabal** [comment]
@rootelement , thank you. Works fine.

cc @lakshmiathreya
