### ISSUE TITLE
 Unable to register on challenge with newly created user. 

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/tc-auth-lib#130]
**Challenge** : https://www.topcoder-dev.com/challenges/2cc872a7-3c09-4d23-b3c1-138f22c7deed
**Credential** : mailmemakar902/P@ssw0rd

Today I have created this user and while trying to register with challenge it is showing below error 

![image](https://user-images.githubusercontent.com/25297859/120971334-3bf20e00-c78c-11eb-968b-c691be201a90.png)

Note : Also data is not populating to other app eg connect app 

![image](https://user-images.githubusercontent.com/25297859/120971522-72c82400-c78c-11eb-883e-9a89b30f66bd.png)

**Comment by sachin-maheshwari** [comment]
@drasticdpk is this related to auth0 changes or related member-api issue ?

**Comment by sachin-maheshwari** [comment]
This is signup data - captured on "identity.notification.create" 
{
  "id": "88774768",
  "modifiedBy": null,
  "modifiedAt": null,
  "createdBy": null,
  "createdAt": null,
  "handle": "sachin07062101",
  "email": "tez.sachin+07062101@gmail.com",
  "firstName": "Sachin",
  "lastName": "Kumar",
  "credential": {
    "activationCode": "xxxxxx",
    "resetToken": null,
    "hasPassword": true
  },
  "profiles": null,
  "status": "U",
  "country": {
    "code": "032",
    "name": "Argentina",
    "isoAlpha2Code": "AR",
    "isoAlpha3Code": "ARG"
  },
  "regSource": null,
  "utmSource": null,
  "utmMedium": null,
  "utmCampaign": null,
  "roles": null,
  "ssoLogin": false,
  "active": false,
  "profile": null,
  "emailActive": false
}

**Comment by sachin-maheshwari** [comment]
Error should be due to different API. 
<img width="1680" alt="Screenshot 2021-06-07 at 12 43 52 PM" src="https://user-images.githubusercontent.com/6467888/120975029-6d6bd900-c78e-11eb-8c4c-2484e1deca70.png">

**Comment by sachin-maheshwari** [comment]
There was kafka consumer( member-api processors) issue at DEV. so i restarted the corresponding processors. It is working fine for me on DEV now.

**Comment by drasticdpk** [comment]
Ok closing this issue. Thank you @sachin-maheshwari
