### ISSUE TITLE
After activating the account if the user tries to click on the Resend button from the 'Welcome to the Topcoder Community!' page we are getting an Unauthorized message

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tc-auth-lib#138]
**Issues**:

- **Bug/or UX (That is not properly handled on the frontend)**: After activating the account if the user tries to click on the Resend button from the 'Welcome to the Topcoder Community!' page we are getting an Unauthorized message. 

![bandicam 2021-06-17 11-33-57-470](https://user-images.githubusercontent.com/42398485/122342152-e4108f80-cf61-11eb-871f-b21bf62bee30.jpg)

https://user-images.githubusercontent.com/42398485/122342107-d78c3700-cf61-11eb-8e69-310d0d383ded.mp4

- **UX**: Different pages are loading. When we click the Activate button the challenge listing page is loading and when we click on the URL the login page is loading. I think this is an inconsistency of the app. Should redirect to the same location and better to redirect the page to the login page

Related Issue: https://github.com/topcoder-platform/tc-auth-lib/issues/136

https://user-images.githubusercontent.com/42398485/122342083-cd6a3880-cf61-11eb-92ca-fb660e419d17.mp4

**Full Registration Flow using GitHub**: 

- Registered via a New GitHub account using the new registration page. After all the registration details are provided (Username country first name and last name ) page is redirected to the confirmation page
- Then I can see an ACTIVATE ACCOUNT  button inside the email (Hope this is the place where we had the issue) but Now I can't double click on the button
- After clicking on the button I will redirect to the challenge listing page
I checked; I can re-login to the app by using the same social login via the login page. 

https://user-images.githubusercontent.com/42398485/122342582-70bb4d80-cf62-11eb-81b9-8f8e252098cc.mp4

**Comment by lakshmiathreya** [comment]
@codejamtc pls update current status on Dev ...

**Comment by lakshmiathreya** [comment]
This is covered in #146
