### ISSUE TITLE
Click on the "Resend" button from the 'Welcome to the Topcoder Community!' is not working

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tc-auth-lib#139]
https://user-images.githubusercontent.com/42398485/122344530-86317700-cf64-11eb-8cf8-1d5b0d28ad95.mp4

1. Open the Login page and go to the registration page
2. Click on GitHub and proceed with the registration
3. Go to the email and check the activation email (Don't click on the activate or the activation link)
4. Wait 3-5mins
5. Now from the 'Welcome to the Topcoder Community!' page click  resend
5. Check the email

**Comment by lakshmiathreya** [comment]
@codejamtc pls update status in Dev now ...

**Comment by codejamtc** [comment]
https://user-images.githubusercontent.com/42398485/123243414-a03cfd80-d500-11eb-861c-e8326054dec4.mp4

**Comment by sachin-maheshwari** [comment]
@lakshmiathreya  same feature is passed on Prod recently - https://github.com/topcoder-platform/tc-auth-lib/issues/146 and we are doing testing on DEV now.

**Comment by lakshmiathreya** [comment]
@codejamtc pls update for Prod since it's deployed already.

**Comment by codejamtc** [comment]
Prod:  🆗 

https://user-images.githubusercontent.com/42398485/123246735-be582d00-d503-11eb-92d2-7d7614cb03c4.mp4
