### ISSUE TITLE
User redirection based on their Type and Resend Email verification

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/tc-auth-lib#145]
Business User : https://connect.topcoder-dev.com/projects?sort=lastActivityAt%20desc
Member User : https://www.topcoder-dev.com/start

**Comment by sachin-maheshwari** [comment]
@drasticdpk I think we should cover the "resend" activation email feature in this issue ? CC @lakshmiathreya

**Comment by drasticdpk** [comment]
**Verification** 
1. User redirection working as expected.

https://user-images.githubusercontent.com/25297859/122943705-f726c380-d396-11eb-8e20-4618192fe823.mp4


2. Resend Functionality Working as expected

https://monosnap.com/file/KAApxOQ9Hh96VkEXtjr4WqEK1IE2QF 

QQ : If user has already activate that email and user click on resend email link we can  see below message, is it expected. @sachin-maheshwari 
https://monosnap.com/file/ChIzIBgKJAP6AZgrXYG7DHjQXj4EuQ

**Comment by drasticdpk** [comment]
**Prod Verification** 

1. Resend Email Functionality 
  
![image](https://user-images.githubusercontent.com/25297859/123213035-3ebb6580-d4e5-11eb-8ca5-2f799ff1fa31.png)
![image](https://user-images.githubusercontent.com/25297859/123213258-8215d400-d4e5-11eb-8500-bba4b93f834c.png)

**Comment by drasticdpk** [comment]
Verified on Prod Env.
