### ISSUE TITLE
Display valid message for Activated User at Resend Link

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/tc-auth-lib#146]
**Steps** 
1. Sign up user and Activate the User
2. Again Click on Resend Link  

**Expected** 
There should be valid message instead of "Resend Email Error"
eg .  "Email already activated"

**Reference** 
![image](https://user-images.githubusercontent.com/25297859/123039878-90df8680-d412-11eb-967c-a79ac65b3e35.png)

https://monosnap.com/file/ChIzIBgKJAP6AZgrXYG7DHjQXj4EuQ

**Comment by sachin-maheshwari** [comment]
@drasticdpk I have fixed from Auth0, please try now.

**Comment by drasticdpk** [comment]
Verified.
![image](https://user-images.githubusercontent.com/25297859/123055793-f8530180-d425-11eb-983f-458b38c30897.png)

Note :  we can change the label if needed later thanks.

**Comment by drasticdpk** [comment]
Verified on prod Env
https://user-images.githubusercontent.com/25297859/123217507-5cd79480-d4ea-11eb-8984-8d593d5b0f27.mp4
