### ISSUE TITLE
[Web-Safari][Functional] Page never loads back after Signup -> Sign up With Google or. Github -> Back on the browser 

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/tc-auth-lib#150]
### Steps to Reproduce
1. Open topcoder.com
2. Click on Signup button and then click on “I’m the Talent” button on User Selection page
3. Now on Signup page click on Either Google or Github
4. Page will redirect to either google’s login page or Github’s login page based on selection in previous step
5. Without filling anything, click on the back button in browser
6. Wait for the page to load
7. Notice the results

### Screenshots or Screen Capture

https://user-images.githubusercontent.com/5712602/123435931-ba073f00-d5eb-11eb-84ea-25489b3fdac3.mov

<img width="1440" alt="Screenshot 2021-06-25 at 7 20 10 PM" src="https://user-images.githubusercontent.com/5712602/123436012-d1462c80-d5eb-11eb-9951-1eea1556dea2.png">

### Current Results
Sign up page never loads back and loading is seen

### Expected Results
Sign up page should load back properly

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Safari Version 13.1 (15609.1.20.111.8)
- OS Version: macOS Catalina 10.15.4

**Comment by drasticdpk** [comment]
Unable to replicate it.

**Comment by drasticdpk** [comment]
https://user-images.githubusercontent.com/25297859/123609878-c96ece00-d81f-11eb-86bf-31054cc7dd99.mp4

**Comment by rprakash20** [comment]
@drasticdpk I am able to replicate the issue now also, could you please check it on the same safari version.



https://user-images.githubusercontent.com/5712602/123636067-0ba50900-d83a-11eb-8b64-27b9cedee1f3.mov

**Comment by drasticdpk** [comment]
Agreed @rprakash20. we are requested to test on latest version of OS/Browser. 
Can you try to update your OS to latest version. 
here I am using this version of browser.

**Comment by drasticdpk** [comment]
![image](https://user-images.githubusercontent.com/25297859/123733356-0f2ca480-d8bb-11eb-967e-51bc5695a59a.png)

**Comment by rprakash20** [comment]
upgrading the OS won't be easy for me atm since only then Safari can be updated. btw Catalina is still in widespread use so, I think if this issue can be reconsidered.
