### ISSUE TITLE
[Web-Safari][Functional]Page never loads back after Login -> Login with Google or. Github -> Back on the browser 

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/tc-auth-lib#151]
### Steps to Reproduce
1. Open topcoder.com
2. Click on Login button 
3. Now on TopCoder Login page click on Either Google or Github
4. Page will redirect to either google’s login page or Github’s login page based on selection in previous step
5. Without filling anything, click on the back button in browser
6. Wait for the page to load
7. Notice the results

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2021-06-25 at 7 19 43 PM" src="https://user-images.githubusercontent.com/5712602/123436182-ffc40780-d5eb-11eb-86f7-9a5ab1a635bd.png">

https://user-images.githubusercontent.com/5712602/123436231-10747d80-d5ec-11eb-960f-e5c3608d74b9.mov

### Current Results
Login page never loads back and loading is seen

### Expected Results
Login page should load back properly

 
**Device**:  Laptop
**Operating System**: Mac OS
**Browser**: Safari

**Comment by drasticdpk** [comment]
@rprakash20 , 
Going forward , please add required label like above. 
Thank you

**Comment by drasticdpk** [comment]
Not able to replicate.

**Comment by rprakash20** [comment]
Same for this, I am able to replicate this as well. Let me know if need to upload another video.
