### ISSUE TITLE
[Web-Safari] Matter is different in Marvel App In respect To Original App

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/tc-auth-lib#152]
1. Device:- Laptop
2.  OS:- macOS
3.  Browser:- Safari
4.  Go To http://topcoder.com/
5.  Click On Sign in 
6. Click on I'AM THE TALENT
7. See Username/Handle then match with Marvel App hence observe.
8.  Actual Result:- Matter is different in Marvel App In respect To Original App
9.  Expected Result:- Matter should be same in Marvel App In respect To Original App too
10. See Screencast & Screenshots:- 
https://user-images.githubusercontent.com/42583358/123437102-f4251080-d5ec-11eb-8140-74ef5e42d355.mp4
![BUG 1 Original](https://user-images.githubusercontent.com/42583358/123437170-030bc300-d5ed-11eb-9922-e60ce71e5f3c.png)
![BUG 1 Marvel](https://user-images.githubusercontent.com/42583358/123437216-0ef78500-d5ed-11eb-9541-eefa9ff9596f.png)

11. ![OS Version](https://user-images.githubusercontent.com/42583358/123436911-c0e28180-d5ec-11eb-927c-489253f2eec2.png)
12. ![Safari Version](https://user-images.githubusercontent.com/42583358/123436946-c93abc80-d5ec-11eb-9039-e83219e4c9ee.png)

**Comment by drasticdpk** [comment]
Please check https://marvelapp.com/prototype/9hihec1/screen/79677899/
