### ISSUE TITLE
Title- Design issue noticed in the Registration Page. 

### ISSUE THREAD

**Issue by samray1103** [topcoder-platform/tc-auth-lib#155]
**Step to Reproduce:** 
Open the URL topcoder.com
Click on Sign UP
Compare with the given Marvel application.

**Actual result**
There is a design issue , In the Marvel app - the google  logo shows first where as in the Topcoder.com , Github logo shows  first. 

**Expected Result:** 

The application design should match with given marvel design.
**Bug Type :** 

Functional

**Device/Browser**
Laptop |
Windows 10 / Chrome Version 87.0.4280.88 (Official Build) (64-bit) |

**Screenshot:**
<img width="1204" alt="Marvel-1" src="https://user-images.githubusercontent.com/83765094/123437628-9a721580-d5ef-11eb-87e5-113f52d18e1a.png">
<img width="1245" alt="1" src="https://user-images.githubusercontent.com/83765094/123437659-a362e700-d5ef-11eb-89d7-9413ebcd608d.png">

**Comment by drasticdpk** [comment]
Agreed but this is expected. So it is not valid issue .
