### ISSUE TITLE
Web : Incorrect text for close

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/tc-auth-lib#156]
Steps:-
1. Enter the url - https://connect.topcoder.com/new-project/talent-as-a-service
2. View the (X)

Issue :  View the (X) - ESC
Expected Result : Text Should be Close

Issue Description : Web :
Device type - Laptop
OS - Windows
Browser user - Chrome

![image](https://user-images.githubusercontent.com/61318135/123437422-46fec800-d5ed-11eb-892e-200e18b21534.png)

**Comment by drasticdpk** [comment]
out of scope.
