### ISSUE TITLE
[Web-Chrome] Stock images and UI missing on I'm the Customer

### ISSUE THREAD

**Issue by hyperblaster1** [topcoder-platform/tc-auth-lib#157]
## Steps to reproduce

1. Open www.topcoder.com
2. Click SIGN UP
3. Click I'm the Customer
4. Currently, on the Login/signup page there are no stock images and Welcome UI

## Screenshot

https://user-images.githubusercontent.com/51795389/123437699-9644f880-d5ed-11eb-868f-cce58644bf6c.mp4

## Actual Result
Stock images and UI missing on I'm the Customer

## Expected Result
Stock images and UI missing should be present

# Bug Type
Useability

## Device | OS | Browser
Desktop |
Windows 10 Build 19042.985 | 
Chrome Version 87.0.4280.88 (Official Build) (64-bit) |

**Comment by drasticdpk** [comment]
Thank you . 
This is expected
![image](https://user-images.githubusercontent.com/25297859/123616441-01790f80-d826-11eb-964b-58f19c824424.png)
