### ISSUE TITLE
Hiring manager email id accepts special charater

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/tc-auth-lib#159]
Issue Description : Web :
Device type - Laptop
OS - Windows
Browser user - Chrome

URL : https://connect.topcoder.com/new-project/talent-as-a-service
Steps - 
1. Enter the Job and mandatory detail
2. Click Next
3.Enter - Hiring Manager and Email Address - with invalid email/special characters
 
Issue : Hiring Manager and Email Address accepts email/special characters
Expected Result : email/special characters should not be accepted for Hiring Manager field.

![image](https://user-images.githubusercontent.com/61318135/123437965-da37fd80-d5ed-11eb-84f5-96690f393130.png)

**Comment by drasticdpk** [comment]
Out of scope.
