### ISSUE TITLE
Sanitize Data where multiple handles use the same email address

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/tc-auth-lib#16]
There are cases where the same email address has been used for multiple profiles in the past. The new Auth0 allows only unique email addresses. There will be an issue with older accounts that share the same email address.

**Comment by SathyaJayabal** [comment]
@sachin-maheshwari , please see video 
I am logging in through my handle : `picachui`, but getting logged in `jaicode`.
jaicode also uses the same email address as picachui.

[42.mov.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5407544/42.mov.zip)

**Comment by sachin-maheshwari** [comment]
As checked on Dev DB, 'email@domain.com.z' email id is associated with more than 80K user. And "new auth", for accessing roles we are fetching it from email id, so its failing due to timeout.

**Comment by mtwomey** [comment]
I'm confused about the failing part? In the video it looks like it succeeds, it just is associating a different account with the login? Marking must-fix for now until we understand this a little better. @SathyaJayabal I am unfamiliar with these accounts with the same email. When or where do we have that happening to your knowledge?

**Comment by SathyaJayabal** [comment]
@mtwomey , I think previously users were allowed to register multiple times with the same email id (a few years back I think). 

What @sachin-maheshwari had suggested was to first find out how many accounts are there in production which do not have a unique email address and then decide on how to fix this.

**Comment by mtwomey** [comment]
@SathyaJayabal I am unclear on why / if this is related to email. I'm watching your video and see you logging in with a username, not an email. The DB connection in auth0 passes that username & password to our identity endpoint. So I'm unclear on how might relate to the email address at all?

Is it possible that this issue (you getting logged in as a different user) is something else and not related to your email? (cc: @sachin-maheshwari )

**Comment by SathyaJayabal** [comment]
@mtwomey, both those handles use the same  email address, and the new auth0 requires unique email accounts for each account. So I concluded that even though I used my handle, the auth0 may have used the email of the account to identify the account and which, may have caused the incorrect logging in.

But you are correct, there could be a chance it is due to something else.

**Comment by sachin-maheshwari** [comment]
Need to change in Identity service

**Comment by sachin-maheshwari** [comment]
@mtwomey as discussed, if you login (regular) from handle, I am picking roles and other info from handle instead of email id. Changes deployed on Identity Service for Dev, will move changes to production by today. 
@SathyaJayabal please check now.

**Comment by sandhiyakavi** [comment]
@sachin-maheshwari Able to correctly login in with the appropriate userhandles used. Verified on Dev with the below Userhandles which share the same email ID topcoderconnect@gmail.com

1.  TCConProgramMgr , Registered Email ID: topcoderconnect+ProgramMgr@gmail.com
2.  TCConnCopilot , Registered Email ID: topcoderconnect+Copilot@gmail.com
3. topcoderconnect , Registered Email ID: topcoderconnect@gmail.com

[multiple_handle_same_email.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5427545/multiple_handle_same_email.zip)

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi looks correct to me. We can change label to qa-pass ?

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi production deployment done. Its ready for QA-Staging.

**Comment by sandhiyakavi** [comment]
@sachin-maheshwari Able to correctly login in with the appropriate userhandles used. Verified on Staging with the below Userhandles which share the same email ID topcoderconnect@gmail.com

CustomerUser , Registered Email ID: topcoderconnect@gmail.com
TCConnCopilot , Registered Email ID: topcoderconnect+Copilot@gmail.com

[Prod_multiple_handle.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5428203/Prod_multiple_handle.zip)

**Comment by SathyaJayabal** [comment]
verified on prod
