### ISSUE TITLE
No error message on Spaces in the name field

### ISSUE THREAD

**Issue by kalindipandey** [topcoder-platform/tc-auth-lib#161]
**Steps to Reproduce**

1. Go to https://connect.topcoder.com/
2. Click on teh sign up 
3. Click on the Signup button without adding name and last name >> add spaces and observe error disappears.

**Actual**

No error message on Spaces in the name field

**Expected**

There should be error message on Spaces in the name field

**Screenshot/Screencast**

![Screenshot 2021-06-25 at 7 49 27 PM](https://user-images.githubusercontent.com/46349625/123438643-8c6fc500-d5ee-11eb-9104-4d507690601e.png)

**Device Info | Browser Info**

MacBook air macOS Big Sur 11.1 | Chrome Version 91

**Comment by drasticdpk** [comment]
Unable to replicate it. 
![image](https://user-images.githubusercontent.com/25297859/123618466-f32bf300-d827-11eb-9966-b454c36e1c99.png)
