### ISSUE TITLE
[Web-Safari] There is no matter Don't have an Account? Sign Up in Original App

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/tc-auth-lib#162]
1. Device:- Laptop
2. OS:- macOS
3. Browser:- Safari
4. Go To https://www.topcoder.com
5. Click On Log In 
6. Click on I'AM THE TALENT
7. Then see matter written below Log in then compare with Marvel App, hence Observe.
9. Actual Result:- There is no matter Don't have an Account? Sign Up in Original App
10. Expected Result:- There should be matter Don't have an Account? Sign Up in Original App
11. See Screencast & Screenshots:-
https://user-images.githubusercontent.com/42583358/123438615-82e65d00-d5ee-11eb-8162-f8802355aad3.mp4
![BUG 2 Marvel ](https://user-images.githubusercontent.com/42583358/123438674-95f92d00-d5ee-11eb-84aa-f3507c3d3c15.png)
![BUG 2 Original](https://user-images.githubusercontent.com/42583358/123438851-bf19bd80-d5ee-11eb-97c0-eeed31514933.png)
12. 
![OS Version](https://user-images.githubusercontent.com/42583358/123438879-c93bbc00-d5ee-11eb-84bc-df675bdcf229.png)
13. 
![Safari Version](https://user-images.githubusercontent.com/42583358/123438910-d3f65100-d5ee-11eb-86ad-d2d4ba626dea.png)

**Comment by drasticdpk** [comment]
This one is our final design. 
https://marvelapp.com/prototype/9hihec1/screen/79677899/
