### ISSUE TITLE
Incorrect error message being shown.

### ISSUE THREAD

**Issue by samray1103** [topcoder-platform/tc-auth-lib#169]
**Step to Reproduce:** 
Open the URL topcoder.com
Click on Sign UP
click on check your email. 
Compare with the given Marvel application.

**Actual result**
Application doesnot highlight the error textbox. Also the error message is not clear enough to track where the error has actually occurred.

**Expected Result:** 
The application should show correct message when user face some problem.
Also it should highlight the text box when the error comes. 

**Bug Type :** 
Functional

**Device/Browser**
Laptop |
Windows 10 / Chrome Version 87.0.4280.88 (Official Build) (64-bit) |

<img width="1095" alt="invalid error message  " src="https://user-images.githubusercontent.com/83765094/123439822-da39fc80-d5f1-11eb-951e-089abd7045e7.png">

**Comment by drasticdpk** [comment]
Steps are mismatch.
