### ISSUE TITLE
The Check your email shows inconsistecy compare with the given Marvel app.

### ISSUE THREAD

**Issue by samray1103** [topcoder-platform/tc-auth-lib#171]
Check your email  content shows different in the application and in Marvel app it shows different. 

![email1](https://user-images.githubusercontent.com/83765094/123440261-4fa5cd00-d5f2-11eb-92a5-c8d906051ecd.png)
![email](https://user-images.githubusercontent.com/83765094/123440273-52a0bd80-d5f2-11eb-9827-3aa525721279.png)

**Comment by samray1103** [comment]
**Step to Reproduce:** 
Open the URL topcoder.com
Click on Sign UP
click on check your email. 
Compare with the given Marvel application.


**Actual result**
Check your email content shows different in the application and in Marvel app it shows different.

**Expected Result:** 
The content should be same as marvel app

**Bug Type :** 
Functional

**Device/Browser**
Laptop |
Windows 10 / Chrome Version 87.0.4280.88 (Official Build) (64-bit) |

**Comment by drasticdpk** [comment]
Duplicate with : https://github.com/topcoder-platform/tc-auth-lib/issues/170
