### ISSUE TITLE
Incorrect warning message on username field

### ISSUE THREAD

**Issue by draco-malfoy** [topcoder-platform/tc-auth-lib#174]
**Device**:
  Laptop

**Operating System**:
 Windows 10

**Browser**: Chrome .

**Steps to reproduce** : 

1. go to sign up page
2. enter all form details
3. in username/handle field, enter blank spaces and click Sign up
4. error message appears saying ''Use **%d-%d** letters, numbers and the following characters: "_", ".", "+", "-""

**Actual result**: 

 **%d-%d** is vague

**Expected results**:

should be alphabets

**Bug Type** : Functional

**Testing collateral**: 

https://user-images.githubusercontent.com/46344490/123440860-dd80b880-d5f0-11eb-8328-e75233c62c26.mp4

![1](https://user-images.githubusercontent.com/46344490/123440887-e5d8f380-d5f0-11eb-9efe-cf231f573b49.PNG)

**Comment by drasticdpk** [comment]
Duplicate
