### ISSUE TITLE
[MS Edge Web] An additional needless icon shows when entering password

### ISSUE THREAD

**Issue by hyperblaster1** [topcoder-platform/tc-auth-lib#178]
## Steps to reproduce

1. Open topcoder.com on MS Edge
2. Click Login
3. Enter any characters in password field
4. Currently, when you do this you will see an additional needless eye icon on top of the original

## Screenshot

https://user-images.githubusercontent.com/51795389/123441326-55e77980-d5f1-11eb-9640-d30ea52c2717.mp4

## Actual Result
An additional non-used icon shows when entering password

## Expected Result
This icon should be removed 

# Bug Type
Useability

## Device | OS | Browser
Desktop |
Windows 10 Build 19042.985 | 
MS Edge Version 91.0.864.59 (Official build) (64-bit)

**Comment by drasticdpk** [comment]
This is Edge browser feature .
you can check for gitlab.com too.
![image](https://user-images.githubusercontent.com/25297859/123625480-8288d480-d82f-11eb-9049-42677f006fc5.png)
