### ISSUE TITLE
[Web-Chrome][Functional] Resetting Password for a non-existing account shows "WE'VE JUST SENT YOU AN EMAIL TO RESET YOUR PASSWORD."

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/tc-auth-lib#179]
### Steps to Reproduce
1. Open topcoder.com
2. Click on Login
3. On Topcoder Login, Click on "Forgot your Password"
4. Enter a non-existing email ID, some random email address or if you an email ID which is not registered with topcoder
5. Click on Send Email
6.  Notice the result

### Screenshots or Screen Capture

https://user-images.githubusercontent.com/5712602/123441524-947d3400-d5f1-11eb-94a1-9a19843ddcbf.mov

### Current Results
Resetting Password for a non-existing account shows "WE'VE JUST SENT YOU AN EMAIL TO RESET YOUR PASSWORD."

### Expected Results
For non-existing email ids, it should say account doesn't exist.

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 91.0.4472.114 (Official Build) (x86_64)
- OS Version: macOS Catalina 10.15.4

**Comment by drasticdpk** [comment]
Invalid.
