### ISSUE TITLE
Error message not displayed if user tries to Sign up without entering a country

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-auth-lib#18]
Description:
Error message not displayed (only textbox is highlighted in red color)  if user tries to Sign up without entering a country.

Expected behaviour: 
Message like  "can't be blank" should be displayed

Screenshot:

![image](https://user-images.githubusercontent.com/55895538/94107551-b0905100-fe78-11ea-8e60-7ecce57144d4.png)

**Comment by drasticdpk** [comment]
duplicate .
