### ISSUE TITLE
[Firefox - Web] Oops!, something went wrong

### ISSUE THREAD

**Issue by Chapre** [topcoder-platform/tc-auth-lib#185]
**Steps to reproduce**
1. go to https://connect.topcoder.com/
2. Sign up new user
3. Fill in valid data and confirm signup
4. Once in the activation confirmation page click back

**Actual Result**
Show oops problem
![image](https://user-images.githubusercontent.com/13720708/123441877-3c800680-d5cc-11eb-8ebf-ac13b538268c.png)

**Expected Result**
Back login page and prompt the user to login again

**Bug Type**
Functional

**Device | OS | Browser**
Desktop |Windows 10 Build 19043.1081 |
Firefox Version 89.0.1

**Comment by drasticdpk** [comment]
Unable to replicate

**Comment by Chapre** [comment]
@drasticdpk 

https://user-images.githubusercontent.com/13720708/123751705-ec48c300-d8af-11eb-8ebf-04dda7166115.mp4
