### ISSUE TITLE
Sign up [UX issue]: Error message displayed for invalid email address

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-auth-lib#19]
Description:
For invalid email address, Error message displayed as "Invalid". Can it be displayed as "Invalid Email address" to be more meaningful?

Screenshot:

![image](https://user-images.githubusercontent.com/55895538/94109897-a5d7bb00-fe7c-11ea-8bff-f5fceff9f930.png)

**Comment by drasticdpk** [comment]
verified.
![image](https://user-images.githubusercontent.com/25297859/124267990-afebc000-db58-11eb-8a7b-77df9fac00a1.png)
