### ISSUE TITLE
[Web-Chrome][UI]"Forgot Password" is active in empty space also in connect.topcoder.com -> Account and security

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/tc-auth-lib#190]
### Steps to Reproduce
1. Open connect.topcoder.com
2. if you are already logged in the click on Account and Security in User Actions in. top right 
3. Or log in and then click on Account and Security
4. Click on empty space near Forgot Password
5. Notice the results

### Screenshots or Screen Capture

https://user-images.githubusercontent.com/5712602/123443513-97792400-d5f3-11eb-83d8-9f357b8e1675.mov

### Current Results
"Forgot Password" is active in empty space also in connect.topcoder.com -> Account and security

### Expected Results
Only the button should be active and when clicked should show reset options

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 91.0.4472.114 (Official Build) (x86_64)
- OS Version: macOS Catalina 10.15.4

**Comment by drasticdpk** [comment]
out of scope
