### ISSUE TITLE
[Web_safari]Key icon is overlapping with Eye icon

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/tc-auth-lib#191]
1. Device:- Laptop
2. OS:- macOS
3. Browser:- Safari
4. Go To https://connect.topcoder.com/
5. Click On Start a project
6. Try to fill with User name & Password then observe in Password field
7. Actual Result:- Key icon is overlapping with Eye icon
8. Expected Result:- Key icon should not overlap with Eye icon
9. https://user-images.githubusercontent.com/42583358/123443623-b081d500-d5f3-11eb-83a6-8262de3e281a.mp4
10. ![BUg 4](https://user-images.githubusercontent.com/42583358/123443687-bf688780-d5f3-11eb-8a0b-8c17c3bb759a.png)
11. ![OS Version](https://user-images.githubusercontent.com/42583358/123443742-cdb6a380-d5f3-11eb-831a-5ce638d98308.png)
12. ![Safari Version](https://user-images.githubusercontent.com/42583358/123443811-ddce8300-d5f3-11eb-9bae-ffb9fea3efb6.png)

**Comment by drasticdpk** [comment]
Browser feature.
