### ISSUE TITLE
[Chrome Web] "Oops something went wrong" when clicking back on success screen

### ISSUE THREAD

**Issue by hyperblaster1** [topcoder-platform/tc-auth-lib#193]
## Steps to reproduce

1. Open topcoder.com on MS Edge
2. Click Sign Up > Click I'm the talent
3. Enter correct details
4. Click Sign Up
5. On the "Check your email" ,click back

## Screenshot

https://user-images.githubusercontent.com/51795389/123444436-841a8880-d5f4-11eb-85f3-854a9dcc516b.mp4

## Actual Result
"Oops something went wrong" when clicking back on success screen

## Expected Result
Should correct the error screen

# Bug Type
Functional

## Device | OS | Browser
Desktop |
Windows 10 Build 19042.985 | 
Chrome Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by drasticdpk** [comment]
https://github.com/topcoder-platform/tc-auth-lib/issues/141
