### ISSUE TITLE
System is taking Name as space

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/tc-auth-lib#2]
**Steps** :
1. Go to https://qa-community-app.topcoder-dev.com/members/TonyJ
2. Click Login button.
3. Go to sign up section 
4. Fill the data (first/last name as space), submit the form and observe the email

**Expected** : 
System should not  take space as first/last  name.
**Reference** 
 
![image](https://user-images.githubusercontent.com/25297859/92591825-514e1080-f2be-11ea-8ed6-07a120415531.png)

![image](https://user-images.githubusercontent.com/25297859/92591938-84909f80-f2be-11ea-9a75-8308d536ef9f.png)

**Comment by sandhiyakavi** [comment]
Issue still exists.Allowing space as firstname and lastname.

[signup_space.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5400103/signup_space.zip)

![image](https://user-images.githubusercontent.com/55895538/96418152-4e373000-122d-11eb-95e5-6aa33b4ffefb.png)

**Comment by sachin-maheshwari** [comment]
Fixed on Dev and Prod. @sandhiyakavi Please verify and close the issue.

**Comment by sandhiyakavi** [comment]
Verified in both Dev and Prod. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/104911542-5d657f80-59ce-11eb-810e-9614fae9d698.png)
