### ISSUE TITLE
Registration using Social sites Fails

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-auth-lib#20]
Description:
Registration using social sites fails. 

After login to the particular social site the window closes and no Confirmation message or mail is displayed. Registration fails.

video:

[Facebook_signup_fails.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5274895/Facebook_signup_fails.zip)

**Comment by sandhiyakavi** [comment]
Adding to the above: Registration through Google is working. Not able to register using other social links.

**Comment by sachin-maheshwari** [comment]
As checked quickly, some social accounts github etc are returning user's email. That is root cause. 
Note - "gmail" is working fine.

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi  There was configuration issue at auth0.  Fixed for dev tenant. Please verify. github and facebook should work now.

**Comment by sandhiyakavi** [comment]
@sachin-maheshwari Verified for Facebook and GitHub .Confirmation message is getting displayed now. But Confirmation mail is not received.
[facebook_signup_retest.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5296529/facebook_signup_retest.zip)

If user tries to login using the same facebook account, it is asking again to enter Userhandle and country.

If same userhandle entered ,then error message displayed like userhandle is already taken. 
Same applies for GitHub as well.

[facebook_login_fails.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5296533/facebook_login_fails.zip)

**Comment by sachin-maheshwari** [comment]
I got the issue for github, firstname and lastname are available in return from github, due to that "ap-notification" (mail sender) falied. 
For reference, pasting ap-notification log below - 
INFO  [2020-09-29 15:50:44,720] com.appirio.notificationservice.util.event.NotificationEventHandler: Exception JSONObject["firstName"] not found.
ERROR [2020-09-29 15:50:44,721] com.appirio.notificationservice.util.event.NotificationEventHandler: JSONObject["firstName"] not found.
! org.json.JSONException: JSONObject["firstName"] not found.

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi also checked for facebook, its working fine for me if i configured unique email (not already present at tc database). And got activation email too. 

So finally issue is :  **github, activation mail not received**.   root cause already shared above.

**Comment by sachin-maheshwari** [comment]
For github first and last name issue, as per internal team discussion, at the time registration, we will show additional fields first and last name along with handle and country and capture that information from intermediate page. CC: @mtwomey

**Comment by sandhiyakavi** [comment]
@sachin-maheshwari The registration through Twitter account is also failing. Getting below screen and no confirmation message or mail is received.

![image](https://user-images.githubusercontent.com/55895538/94774439-e6918000-03f8-11eb-8b33-806e2d83eaa3.png)

[Registration_through Twitter.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5309794/Registration_through.Twitter.zip)
[Twiiter_not registering.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5309790/Twiiter_not.registering.zip)

**Comment by sachin-maheshwari** [comment]
As checked quickly, Twitter is not sharing email. That is root cause. We need to handle this special case differently.

**Comment by sandhiyakavi** [comment]
verified. Signup working for all social sites.

[Google_signup.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5383968/Google_signup.zip)
[GitHub_signup.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5383969/GitHub_signup.zip)
[facebook_signup.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5383971/facebook_signup.zip)

**Comment by sandhiyakavi** [comment]
Verified in Prod

[github_signup_Prod.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5486797/github_signup_Prod.zip)
[google_signup_Prod.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5486798/google_signup_Prod.zip)
