### ISSUE TITLE
[Web][Functional] Reset password without filling in the password fields in connect shows Network error

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/tc-auth-lib#201]
### Steps to Reproduce
1. Open connect.topcoder.com
2. Login with user credentials
3. Click on My Profile -> Account & Security
4. Click on Forgot Password
5. Click on Reset password without filling in anything in the password fields
6. Notice the error.

### Screenshots or Screen Capture

<img width="1439" alt="Screenshot 2021-06-25 at 8 45 29 PM" src="https://user-images.githubusercontent.com/5712602/123446570-a57c7400-d5f6-11eb-8b6d-269b4c804420.png">

### Current Results
Reset password without filling in the password fields in connect shows Network error

### Expected Results
Reset password without filling in the password fields should show valid error

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 91.0.4472.114 (Official Build) (x86_64)
- OS Version: macOS Catalina 10.15.4

**Comment by drasticdpk** [comment]
Agreed but this is out of scope.
