### ISSUE TITLE
[Edge Web] Additional right arrow icon shows when user clicks "Send Email"

### ISSUE THREAD

**Issue by hyperblaster1** [topcoder-platform/tc-auth-lib#208]
## Steps to reproduce

1. Open topcoder.com on MS Edge
2. Click Login
3. Click Forgot password
4. Enter 'a@a.com'
5. Click Send Email
6. Observe that an additional right arrow icon shows when you do that

## Screenshot

https://user-images.githubusercontent.com/51795389/123447954-0b1d3000-d5f8-11eb-97b5-2f3baf14116a.mp4

## Actual Result
Additional right arrow icon shows when you click "Send Email"

## Expected Result
This icon should be removed 

# Bug Type
Useability

## Device | OS | Browser
Desktop |
Windows 10 Build 19042.985 | 
MS Edge Version 91.0.864.59 (Official build) (64-bit)

**Comment by drasticdpk** [comment]
duplicate
