### ISSUE TITLE
[Chrome Web] Check your email screen has old favicon

### ISSUE THREAD

**Issue by hyperblaster1** [topcoder-platform/tc-auth-lib#210]
## Steps to reproduce

1. Open topcoder.com on Chrome
2. Click Sign Up > Click I'm the talent
3. Enter valid values in form and Click Sign Up
4. On the Check you email screen , note that the favicon is of the old topcoder website

## Screenshot
https://user-images.githubusercontent.com/51795389/123448417-82eb5a80-d5f8-11eb-803a-97054face522.mp4

## Actual Result
Check your email screen has old favicon

## Expected Result
This icon should be updated

# Bug Type
Useability

## Device | OS | Browser
Desktop |
Windows 10 Build 19042.985 | 
Chrome Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by drasticdpk** [comment]
https://accounts-auth0.topcoder.com/ 
This app has that favicon icon.
