### ISSUE TITLE
[Web][UI]Error message for handle more than 15 characters should be corrected

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/tc-auth-lib#213]
### Steps to Reproduce
1. Open topcoder.com
2. Click on Sign Up -> I'm The Talent
3. On Sign up, Choose a Username/Handle greater than 15 chars
4. Fill in other details
5. Click on Sign Up
6. Notice the error message

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2021-06-25 at 9 06 21 PM" src="https://user-images.githubusercontent.com/5712602/123449514-64d22a00-d5f9-11eb-825a-0175818656d9.png">

### Current Results
Error message shown is : "LENGTH OF HANDLE IN CHARACTER SHOULD BE BETWEEN 2 AND 15". Sentence's English looks wrong and confusing.

### Expected Results
Error message for handle more than 15 characters should be corrected. 

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 91.0.4472.114 (Official Build) (x86_64)
- OS Version: macOS Catalina 10.15.4

**Comment by drasticdpk** [comment]
duplicate
