### ISSUE TITLE
Web Chrome :On providing invalid email/user gets message - user already exists

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/tc-auth-lib#215]
Steps:-
1. Click on link - https://auth.topcoder.com/login?
2. Click on Signup
3. Enter invalid user
4.Click SignUp

Issue : Gets message "User already exists"
Expected Result : Should not be able to register. Nor should get this message

Issue Description : Web :
Device type - Laptop
OS - Windows
Browser user - Chrome

![image](https://user-images.githubusercontent.com/61318135/123448015-1708f200-d5f8-11eb-8b85-a63a8b62ca58.png)

**Comment by drasticdpk** [comment]
![image](https://user-images.githubusercontent.com/25297859/123776152-bd9e0d00-d8ee-11eb-85ee-4548000f8f75.png)
