### ISSUE TITLE
[Chrome Web] Email entered on Sign Up is copied to forgot your password section

### ISSUE THREAD

**Issue by hyperblaster1** [topcoder-platform/tc-auth-lib#216]
## Steps to reproduce

1. Open topcoder.com on MS Edge
2. Click Sign up >click i'm the talent
3. Enter an email in Sign Up page > Switch to Login > Click Forgot password ?
4. Value from sign up is copied here

## Screenshot
https://user-images.githubusercontent.com/51795389/123450832-c2b34180-d5fa-11eb-8210-ba56030f2c38.mp4

## Actual Result
Email entered on Sign Up is copied to forgot your password section

## Expected Result
Reset password should have empty fields

# Bug Type
Useability

## Device | OS | Browser
Desktop |
Windows 10 Build 19042.985 | 
Chrome Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by drasticdpk** [comment]
duplicate
