### ISSUE TITLE
[Chrome Web] Email entered on Forgot Password is copied on it's own on Sign Up page

### ISSUE THREAD

**Issue by hyperblaster1** [topcoder-platform/tc-auth-lib#218]
## Steps to reproduce

1. Open topcoder.com 
2. Click Login > Click Forgot Password
3. Enter email address in field > Click Back > Switch to Sign Up page
4. Value from Forgot Password is copied to Sign Up page

## Screenshot
https://user-images.githubusercontent.com/51795389/123451440-3a816c00-d5fb-11eb-8606-05de7c68a2fb.mp4

## Actual Result
Email entered on Forgot Password is copied on it's own on Sign Up page

## Expected Result
Value should not be copied from forgot password to sign up page, it does not make sense

# Bug Type
Useability

## Device | OS | Browser
Desktop |
Windows 10 Build 19042.985 | 
Chrome Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by drasticdpk** [comment]
duplicate
