### ISSUE TITLE
[Web-Chrome] - Check your email Page - Link text difference between Marvel and App

### ISSUE THREAD

**Issue by InfantaAnu** [topcoder-platform/tc-auth-lib#219]
**Device:** Laptop
**Operating System:** Windows 10 Home - 20H2 - 19042.1052
**Browser:** Chrome
**Steps to reproduce :**

1. Go to https://www.topcoder.com/
2. Click on Log In Button
3. Click on Sign Up tab
4. Fill the fields and click Sign Up button
5. Notice the difference between the link text in Marvel and App

**Actual result:** Link text difference between Marvel and App 
![APP](https://user-images.githubusercontent.com/34676216/123451603-48cf8800-d5fb-11eb-9542-760a62373b40.png)

**Expected results:** Consistent behavior of link text between Marvel and App
![MARVEL](https://user-images.githubusercontent.com/34676216/123451633-4f5dff80-d5fb-11eb-897e-1aabba8d2fe3.png)

**Bug Type:** Functional
**Marvel:** https://marvelapp.com/prototype/9hihec1/screen/79678839/

**Comment by drasticdpk** [comment]
duplicate
