### ISSUE TITLE
[Chrome]  First name and Last name accepts special characters

### ISSUE THREAD

**Issue by neenatc** [topcoder-platform/tc-auth-lib#225]
Steps to reproduce

1. Open topcoder.com 
2. Click Register Now
3. Click on Sign Up
4. Enter ######## in First name field
5. Enter $$$$$$$$ in Last name field 
6. It is accepted and the message displayed is "User already exists"

Screenshot
 
![Issue 2](https://user-images.githubusercontent.com/83340672/123454529-4b7fac80-d5fe-11eb-89b2-b0b7896a042f.png)
![Issue 2 image 2](https://user-images.githubusercontent.com/83340672/123454538-4f133380-d5fe-11eb-94a5-95db6072aefd.png)

Actual Result
Special characters are accepted in First name and Last name field

Expected Result
Special Characters cannot be accepted in First name and Last name field 

Bug Type
Functional

Device : Laptop 
OS : Microsoft Windows 10 Home Version	10.0.19042 Build 19042
Browser : Chrome Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by drasticdpk** [comment]
The message is for username.
