### ISSUE TITLE
Page becomes unstable on clicking logout from the Online Review (OR) app

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-auth-lib#23]
Description:
Page becomes unstable on clicking logout from the Online Review (OR) app

[OR_logout_unstable.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5282196/OR_logout_unstable.zip)

**Comment by sachin-maheshwari** [comment]
will track here - https://github.com/topcoder-platform/tc-auth-lib/issues/26
