### ISSUE TITLE
[Web - Chrome] The login details get copied on the signup form

### ISSUE THREAD

**Issue by kalindipandey** [topcoder-platform/tc-auth-lib#230]
**Steps**

1. Go to https://connect.topcoder.com/
2. click on the login button 
3. see that login takes the saved credentials >> click on the signup >> observe that the login form data goes to the signup form 

**Actual**

The login details get copied on the signup form

**Expected**

The login details should not get copied on the signup form

**Screenshot/Screencast**

https://user-images.githubusercontent.com/46349625/123457704-d01ffa00-d601-11eb-965e-1f77d6b65e05.mp4

**Device Info | Browser Info**

MacBook air macOS Big Sur 11.1 | Chrome Version 91

**Comment by drasticdpk** [comment]
duplicate
