### ISSUE TITLE
[Android-mobile-functional] Undesirable logout after login on mobile

### ISSUE THREAD

**Issue by Chapre** [topcoder-platform/tc-auth-lib#234]
**Steps to reproduce**
1. Login to by click following link [https://connect.topcoder.com/](https://connect.topcoder.com/) using your mobile
2. Perform whatever login method you want
3. Once logged in press on the back button at the top left corner

**Actual Result**
Topcoder web app exit with a unknown login/logout status
https://user-images.githubusercontent.com/13720708/123458375-e4053500-d5dc-11eb-91f5-2ad284015106.mp4

**Expected Result**
When a back button is pressed and there is nothing in the app history to pop back to; inform the user that the app is exiting.
Obviously if confirmed, the process should logout the user

**Bug Type**
Functional

**Device | OS | Browser**
Samsung S9+|Android version 10|
Chrome *1.0.4472

**Comment by drasticdpk** [comment]
you have to login from browser itself.
