### ISSUE TITLE
[Web][UI]No green tick for fields after filling in correct details on Sign Up, design has green ticks for fields with valid data

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/tc-auth-lib#236]
### Steps to Reproduce
1. Open topcoder.com
2. Click on Sign Up -> I'm The talent
3. Fill the correct details in Sign UP form
4. Notice if there is any green tick showing up in the form for the fields with correct details
5. Check the design at https://marvelapp.com/prototype/9hihec1/screen/78808659

### Screenshots or Screen Capture
<img width="1438" alt="Screenshot 2021-06-25 at 10 34 00 PM" src="https://user-images.githubusercontent.com/5712602/123460838-e4fe8c80-d605-11eb-9408-23e9d4167592.png">
<img width="1439" alt="Screenshot 2021-06-25 at 10 35 04 PM" src="https://user-images.githubusercontent.com/5712602/123460863-eaf46d80-d605-11eb-86dd-1b79618483f5.png">

### Current Results
green tick for fields after filling in correct details on Sign Up, design has green ticks for fields with valid data

### Expected Results
green tick for fields after filling in correct details on Sign Up as per the design  for fields with valid data

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 91.0.4472.114 (Official Build) (x86_64)
- OS Version: macOS Catalina 10.15.4

**Comment by drasticdpk** [comment]
https://github.com/topcoder-platform/tc-auth-lib/issues/220
