### ISSUE TITLE
Refresh Token error in Connect, Direct and OR apps

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-auth-lib#24]
Description:
Refresh Token console error in Connect, Direct and OR apps

Steps to Reproduce:
1. login to the respective app (Connect/Direct/OR) using auth0.
2. Wait for 10 mins.
3. Refresh Token error appears in the console.

Screenshot:

<img width="959" alt="Connect_refreshtoken_error" src="https://user-images.githubusercontent.com/55895538/94263958-d862e000-ff70-11ea-9f40-9c16be728b80.png">
<img width="960" alt="Direct_refreshtoken_error" src="https://user-images.githubusercontent.com/55895538/94263974-ddc02a80-ff70-11ea-84fa-4aac5ea9ad0d.png">
<img width="960" alt="OR_refreshtoken_error" src="https://user-images.githubusercontent.com/55895538/94263985-e0bb1b00-ff70-11ea-86f6-b465ad35708c.png">

cc: @RishiRajSahu

**Comment by sandhiyakavi** [comment]
cc: @vikasrohit

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi  I think that case, we need to reload the UI and verify again. Issue could be if from other tab cookies are deleted/logout triggered/happened.

**Comment by sandhiyakavi** [comment]
@sachin-maheshwari I reloaded the UI and verified again. Below are the observations,

Connect app: Getting blank screen after refresh which should not happen. (similar to community app)

<img width="960" alt="connect_refresh_blank screen" src="https://user-images.githubusercontent.com/55895538/94515467-91216b80-025e-11eb-8977-4573dcd3edb9.png">

OR app: Refresh token error is still displaying in the console though blank screen not displayed.

<img width="960" alt="OR_refresh_error_exists" src="https://user-images.githubusercontent.com/55895538/94515583-cc239f00-025e-11eb-9090-159461d662c7.png">

Direct app: The login screen with the mail id used is displayed to login again. This is expected for all apps right?

<img width="960" alt="direct_refreshtoken_login" src="https://user-images.githubusercontent.com/55895538/94515665-0ab95980-025f-11eb-9bc6-600854cbae51.png">

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi I fixed something for this. Please verify. Any specific scenario its happening or general ?

**Comment by sandhiyakavi** [comment]
@sachin-maheshwari  As per my observation, this issue exists only in Incognito/private window.( I used Chrome incognito window to test).

In Normal chrome window.It is displaying fine without any error (before as well as after refresh).

<img width="960" alt="After_refresh_Connect app" src="https://user-images.githubusercontent.com/55895538/94645114-fbe9aa00-0325-11eb-92d1-9067b39d4c4d.png">

**Comment by SathyaJayabal** [comment]
Following error on refreshing the listings page in community app after 10 mins. The error occurs only for chrome incognito mode.
<img width="1440" alt="Screenshot 2020-09-30 at 11 07 16 AM" src="https://user-images.githubusercontent.com/58783823/94647068-575b6e00-030d-11eb-8d64-d59d7f734237.png">

**Comment by SathyaJayabal** [comment]
@sandhiyakavi @sachin-maheshwari , issue is resolved in chrome incognito mode after updating the chrome settings to allow all cookies (previously 3rd party cookies were blocked in incognito mode0

<img width="1440" alt="Screenshot 2020-09-30 at 12 07 10 PM" src="https://user-images.githubusercontent.com/58783823/94652679-1026aa80-0318-11eb-930b-bb4b89a32b1d.png">

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi lets close this issue ?
