### ISSUE TITLE
[Web - safari] The user gets "reset password email" success message when the email is invalid format

### ISSUE THREAD

**Issue by kalindipandey** [topcoder-platform/tc-auth-lib#240]
**Steps**

1. Go to https://www.topcoder.com
2.  Click on the login
3. Click on the forgot password link >> add "@k.com" in the Email field and click on the send email button >> observe that the User get the success message

**Actual**

The user gets "reset password email" success message when the email is invalid format

**Expected**

The user should not get  "reset password email" success message when the email is invalid format

**Screenshot/Screencast**

https://user-images.githubusercontent.com/46349625/123464194-22651900-d60a-11eb-884c-9f94dbc21989.mp4

**Device Info | Browser Info**

MacBook air macOS Big Sur 11.1 | safari 14

**Comment by drasticdpk** [comment]
duplicate
