### ISSUE TITLE
[Chrome Android] User type selection UI is not aligned

### ISSUE THREAD

**Issue by hyperblaster1** [topcoder-platform/tc-auth-lib#244]
## Steps to reproduce

1. Open topcoder.com on chrome on android
2. Click Login > Click Sign Up
3. The User Type selection UI is not vertically aligned 

## Screenshot
https://user-images.githubusercontent.com/51795389/123467873-a0c3ba00-d60e-11eb-8c6a-4d555ce0a67a.mp4

## Actual Result
User type selection UI is not aligned

## Expected Result
UI to be aligned

# Bug Type
Useability

## Device | OS | Browser
Samsung M51 |
Android 11 | 
Chrome Version 91.0.4472.120

**Comment by drasticdpk** [comment]
More details was required
