### ISSUE TITLE
Getting "Unknown error from provider" while trying to generate the V2 Token using Postman

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tc-auth-lib#253]
![bandicam 2021-06-30 09-59-21-797](https://user-images.githubusercontent.com/42398485/123902111-de677080-d989-11eb-8909-a87d7775c3a6.jpg)

**Response**: 401 Unauthorized

```
{
    "error": "Unknown error from provider",
    "error_description": "Unknown error from provider"
}
```

cc @ThomasKranitsas @lakshmiathreya

**Comment by jmgasper** [comment]
@sachin-maheshwari / @lakshmiathreya - Is this truly a p1?  Who is still using v2 tokens?

@codejamtc - What URL is being configured in Postman for `AUTH_V2_URL`?

**Comment by codejamtc** [comment]
@jmgasper ohh, this is fixed now

**Comment by sachin-maheshwari** [comment]
@lakshmiathreya just FYI, that is not related to "Topcoder SignIn/SignUp",  it was at "automation" on DEV env, which is fixed.
