### ISSUE TITLE
Logout functionality not working in OR app.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-auth-lib#26]
Description:

Logout functionality not working in OR app.
[OR_logout.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5298549/OR_logout.zip)

**Comment by sachin-maheshwari** [comment]
Fixed for OR on dev - https://github.com/appirio-tech/docker-nginx-supply/commit/3e9275c46fae43c652b8478f7a7072315837f8fd

**Comment by sachin-maheshwari** [comment]
Unstable page - https://github.com/topcoder-platform/tc-auth-lib/issues/23 existing in current system as well. Need to control from Nginx end.

**Comment by sandhiyakavi** [comment]
@sachin-maheshwari Verified. Logout in OR app is working now.

[logout_OR_working.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5303103/logout_OR_working.zip)

**Comment by sandhiyakavi** [comment]
The OR app is becoming unstable while trying to login using the project details page (https://software.topcoder-dev.com/review/actions/ViewProjectDetails?pid=30057283).

[flickering image.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5406982/flickering.image.zip)

**Comment by sachin-maheshwari** [comment]
It is working fine at my end. Please recheck.

**Comment by sandhiyakavi** [comment]
@sachin-maheshwari This issue is intermittent one. It is working sometimes and sometimes not.

Today also I faced the same issue.

[flickering.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5413291/flickering.zip)

**Comment by mtwomey** [comment]
@sachin-maheshwari I'm marking this one as must-fix because, really - we either have to have high confidence that it won't happen, or we need to identify and fix. If users start complaining of this after the cut-over and the only fix for them is to clear their browser cache, that will force us to roll-back the cut-over (and we don't want to do that).

**Comment by sandhiyakavi** [comment]
Verified. Login and Logout is working fine now

[OR_auth0_pass.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5420058/OR_auth0_pass.zip)

**Comment by sandhiyakavi** [comment]
Verified on Prod.

[OR_logout.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5474498/OR_logout.zip)
