### ISSUE TITLE
Wipro SSO : User handles are getting created same as their email

### ISSUE THREAD

**Issue by sachin-maheshwari** [topcoder-platform/tc-auth-lib#263]
Topgear team reported this issue.

**Comment by lakshmiathreya** [comment]
<img width="661" alt="Screenshot 2021-08-16 at 5 17 03 PM" src="https://user-images.githubusercontent.com/51733042/129578248-029f9658-b4d0-4651-9f48-7ffaff95a036.png">

**Comment by lakshmiathreya** [comment]
Latest registrations post release observed by @sachin-maheshwari

**Comment by sachin-maheshwari** [comment]
@lakshmiathreya If everything is fine, please close this issue.
