### ISSUE TITLE
Topgear to Topcoder redirection Issue for Challenge Listings and Details pages

### ISSUE THREAD

**Issue by lakshmiathreya** [topcoder-platform/tc-auth-lib#265]
-- Non logged in Topgear member - after login - is redirected to Topgear home page instead of the respective Challenge Listings or Details page they accessed prior to login. 
![image](https://user-images.githubusercontent.com/51733042/129857034-1f122088-e7b9-44c9-9ffd-d6a5d986c82e.png)
cc @SathyaJayabal

**Comment by sachin-maheshwari** [comment]
@lakshmiathreya I think issue is not related this repo. 
I think, we worked on previously on this kind of issue here - https://github.com/topcoder-platform/community-app/issues/5576 https://github.com/topcoder-platform/community-app/issues/5565

**Comment by sachin-maheshwari** [comment]
@lakshmiathreya as you moved, please close this issue from here.
