### ISSUE TITLE
OR app: Login through All open projects page directing user to TC site.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-auth-lib#27]
Description:

Login through All open projects page of OR app directing user to TC site.

Steps:
1. Go to 
https://software.topcoder-dev.com/review/actions/ListProjects?scope=all
2. Click Login link.
3. Check the redirected url.

Expected result:
User should again land on the All open projects page of OR app.

[OR_Allopenprojects_page.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5305193/OR_Allopenprojects_page.zip)

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi fixed.

**Comment by sandhiyakavi** [comment]
@sachin-maheshwari Verified. After login the page is now redirected to main OR page.(My projects page).

[OR_login_redirection.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5309467/OR_login_redirection.zip)
