### ISSUE TITLE
UX changes

### ISSUE THREAD

**Issue by sachin-maheshwari** [topcoder-platform/tc-auth-lib#271]
Need change the signup according to attached layout.  

![Screen Shot 2021-09-22 at 8 56 08 AM (1)](https://user-images.githubusercontent.com/6467888/135087535-e65fba05-1ad2-469f-bcc4-176148628832.png)

And at intermediate page too, for enterprise and social login - https://accounts-auth0.topcoder-dev.com/signup.html 

Following changes made at above screen - 
the order of fields is adjusted
the labels (hint) text in three fields change to :

- Create a Username / Handle
- Create a Password
- Select your country (current location) (text wrapping allow)
- one field from the current form is removed (How did you hear about us?)
- the agreement verbiage for Privacy and Terms is changed

**Comment by lakshmiathreya** [comment]
Verified the changes in Dev as per the requirements above.

**Comment by lakshmiathreya** [comment]
@sachin-maheshwari please clarify regarding the requirement for current location hint in the Country field ...
<img width="1680" alt="Screenshot 2021-09-29 at 5 33 09 PM" src="https://user-images.githubusercontent.com/51733042/135265283-e887f892-1499-43da-98b4-a5de9d1d44e7.png">

**Comment by lakshmiathreya** [comment]
Current location hint is no longer a requirement. Closing the Issue.
