### ISSUE TITLE
Unable to find out social login other than google 

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/tc-auth-lib#3]
**Steps** :
1. Go to https://accounts-auth0.topcoder-dev.com/?retUrl=https%3A%2F%2Fqa-community-app.topcoder-dev.com%2Fmembers%2FTonyJ&utm_source=community-app-main
2. Observe the social Login Section

**Expected** : 
All social login option should be display.

**Reference** 
 
![image](https://user-images.githubusercontent.com/25297859/92597827-a80c1800-f2c7-11ea-8999-f68dc159cf1c.png)

![image](https://user-images.githubusercontent.com/25297859/92598194-32547c00-f2c8-11ea-87ec-3522870434f0.png)

**Comment by sachin-maheshwari** [comment]
Bitbucket is issue (looks like coming default), need to fix from auth0 end. 
Added remaining - Twitter, Facebook and Github.
