### ISSUE TITLE
Registration: Harcoded text in Welcome mail

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-auth-lib#31]
Description:

Able to view Harcoded text in Welcome mail .

![image (6)](https://user-images.githubusercontent.com/55895538/95044750-359e2480-071b-11eb-8efd-8634d6db0a35.png)

**Comment by mtwomey** [comment]
Please confirm if this is new behavior for the new auth or if it is existing behavior.

**Comment by SathyaJayabal** [comment]
Mail looks good in prod
[Gmail - Welcome to Topcoder.pdf.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5415543/Gmail.-.Welcome.to.Topcoder.pdf.zip)

**Comment by sandhiyakavi** [comment]
Verified on Prod.
