### ISSUE TITLE
Community app: User details not displayed after logging in using auth0.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-auth-lib#32]
Description: 

User details not displayed after logging in community app using auth0.

<img width="959" alt="community_loginissue" src="https://user-images.githubusercontent.com/55895538/95301678-e0e5df80-08bb-11eb-9da7-a7b4954ef2bb.png">

![image](https://user-images.githubusercontent.com/55895538/95301706-ee02ce80-08bb-11eb-98b8-b42baa3c2c86.png)

**Comment by SathyaJayabal** [comment]
fixed
<img width="1440" alt="Screenshot 2020-10-19 at 12 41 54 PM" src="https://user-images.githubusercontent.com/58783823/96412956-81b39380-1208-11eb-9a92-71c7452f2cc3.png">

**Comment by sandhiyakavi** [comment]
Verified on Prod.

![image](https://user-images.githubusercontent.com/55895538/97858935-39858c80-1d43-11eb-9a47-3b1859612e2a.png)
