### ISSUE TITLE
Error messages are not visible

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tc-auth-lib#34]
![image](https://user-images.githubusercontent.com/42398485/95421383-0675f600-095b-11eb-8fd0-233216d2dc7b.png)

### Steps to reproduce the problem

1. Open https://accounts-auth0.topcoder-dev.com/?retUrl=https%3A%2F%2Fqa-community-app.topcoder-dev.com%2Fmembers%2FTonyJ&utm_source=community-app-main
2. Click Login

### Actual behavior
- Error messages are not visible

### Expected behavior
- Should display the messages properly

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.121

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/96245864-745a9700-0fc5-11eb-9806-421ba447a1e0.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod.

![image](https://user-images.githubusercontent.com/55895538/97857556-45704f00-1d41-11eb-854a-de0d8a0089bd.png)
