### ISSUE TITLE
When user click Logout; page won't redirected to the login page

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tc-auth-lib#35]
![image](https://user-images.githubusercontent.com/42398485/95421579-4806a100-095b-11eb-9c81-94735c80253f.png)

### Steps to reproduce the problem

1. Open https://accounts-auth0.topcoder-dev.com/?retUrl=https%3A%2F%2Fqa-community-app.topcoder-dev.com%2Fmembers%2FTonyJ&utm_source=community-app-main
2. Login using FB accounts
3. Logout

### Actual behavior
- When user click Logout; page won't redirected to the login page

### Expected behavior
- Should redirect the page to the auth0 login page after logout

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.121

**Comment by codejamtc** [comment]
Now redirected to https://www.topcoder-dev.com/

**Comment by sandhiyakavi** [comment]
Verified on Prod.

[Logout.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5474219/Logout.zip)
