### ISSUE TITLE
User is not able to login with the Twitter account

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tc-auth-lib#36]
![image](https://user-images.githubusercontent.com/42398485/95433233-4ba32380-096d-11eb-80f4-92dc85db37d0.png)

### Steps to reproduce the problem

1. Open https://accounts-auth0.topcoder-dev.com/?retUrl=https%3A%2F%2Fqa-community-app.topcoder-dev.com%2Fmembers%2FTonyJ&utm_source=community-app-main
2. Login using Twitter accounts

### Actual behavior
- User is not able to loin with the Twitter account

### Expected behavior
- Should be able to login with the twitter account

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.121

**Comment by sandhiyakavi** [comment]
Closing the issue as Twitter account is not supported.
