### ISSUE TITLE
User is getting topcoder handle and country popup always while login

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tc-auth-lib#37]
![image](https://user-images.githubusercontent.com/42398485/95433559-bb191300-096d-11eb-88ce-84e79bc2404b.png)

### Steps to reproduce the problem

**NOTE: You should have two accounts;**
1. testgoogle@gmail.com (Handle `testgoogle`) - Register account via Google (testgoogle@gmail.com have a Google account and Github account)
2. testgithub@gmail.com (Handle `testgithub`) - Register account via GitHub (testgithub@gmail.com have a Google account and Github account)

1. Open https://challenges.topcoder-dev.com/
2. Click `Sign Up` from the Auth0 login page
3. Select `GitHub` 
4. Enter the credentials of `testgoogle@gmail.com`
5. Authorize 
6. You will get a form (First and Last name, Country and Handle) - I think we are getting this because this account is registered via Google not via GitHub)
7.  Put anything on the fields and proceed
8. Logged into the system as `testgoogle`

Same thing happens when we perform;

1. Open https://challenges.topcoder-dev.com/
2. Click `Sign Up` from the Auth0 login page
3. Select `Google` 
4. Enter the credentials of `testgithub@gmail.com`
5. Authorize 
6. You will get a form (Country and Handle) - I think we are getting this because this account is registered via GitHub not via Google)
7.  Put anything on the fields and proceed
8. Logged into the system as `testgithub`

### Actual behavior
- User is getting topcoder handle and country popup always while login

### Expected behavior
- Should not display always since the user is already registered

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.121

**Comment by sandhiyakavi** [comment]
Similar is happening for Facebook and GitHub if user tries to login using social sites with the already registered email address

[Github_login.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5390421/Github_login.zip)
[fb_login.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5390422/fb_login.zip)

**Comment by codejamtc** [comment]
@sachin-maheshwari Updated the ticket description, Please check

**Comment by mtwomey** [comment]
I see - so two different social accounts, and both social accounts have the same email-of-record for the person. However if you sign in different times with both those accounts, it gets treated like two separate accounts on the Topcoder side. I think this is also the existing behavior, can we verify if that's the case?

**Comment by sachin-maheshwari** [comment]
Now we are giving this error in pop-up - "Social Registration Error: Email address 'soorooshchabokroo@gmail.com' has already been registered, please use another one. Please retry."
