### ISSUE TITLE
Doe not consistent hyperlink with in the application. 

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/tc-auth-lib#4]
**Steps** :
1. Go to https://accounts-auth0.topcoder-dev.com/?retUrl=https%3A%2F%2Fqa-community-app.topcoder-dev.com%2Fmembers%2FTonyJ&utm_source=community-app-main
2. observe the `Don't remember your password?`

**Expected** : 
All Hyperlink text should be consistent in side the application.

**Reference** 
 
![image](https://user-images.githubusercontent.com/25297859/92600033-c1fb2a00-f2ca-11ea-8444-e8219fb3fbd8.png)

**Comment by sandhiyakavi** [comment]
Verified. Still displayed in Black color.

![image](https://user-images.githubusercontent.com/55895538/96418367-a1a97e00-122d-11eb-947b-449422630066.png)

**Comment by drasticdpk** [comment]
Verified.
![image](https://user-images.githubusercontent.com/25297859/124269305-71570500-db5a-11eb-9365-fe55a2db30a7.png)
