### ISSUE TITLE
Registration page validation messages are not displayed properly

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tc-auth-lib#40]
![image](https://user-images.githubusercontent.com/42398485/95558512-f4b45180-0a33-11eb-8910-e28f2a40807b.png)

### Steps to reproduce the problem

1. Open https://accounts-auth0.topcoder-dev.com/?retUrl=https%3A%2F%2Fqa-community-app.topcoder-dev.com%2Fmembers%2FTonyJ&utm_source=community-app-main
2. Click Sign Up
3. Click Sign Up

### Actual behavior
- Registration page validation messages are not displayed properly

### Expected behavior
- Should display the validation messages properly

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.121

**Comment by sandhiyakavi** [comment]
Verified on Prod.

![image](https://user-images.githubusercontent.com/55895538/97854037-4357c180-1d3c-11eb-875a-5ceac75878ea.png)
