### ISSUE TITLE
Some countries on the country list is not visible

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tc-auth-lib#41]
![image](https://user-images.githubusercontent.com/42398485/95561697-bc634200-0a38-11eb-8c13-ce1f28618236.png)

### Steps to reproduce the problem

1. Open https://accounts-auth0.topcoder-dev.com/?retUrl=https%3A%2F%2Fqa-community-app.topcoder-dev.com%2Fmembers%2FTonyJ&utm_source=community-app-main
2. Click Sign Up
3. Click Country field
4. Go to last item

### Actual behavior
- Some countries on the country list is not visible

### Expected behavior
- Should display the last items

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.121

**Comment by sandhiyakavi** [comment]
Verified on Prod.

![image](https://user-images.githubusercontent.com/55895538/97853672-c6c4e300-1d3b-11eb-9b19-9b04e6214f0a.png)
