### ISSUE TITLE
[WM] When I try to login with an existing Copilot account; I am not able to login

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tc-auth-lib#44]
[1.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5377683/1.zip)

![image](https://user-images.githubusercontent.com/42398485/95981153-d7202700-0e3b-11eb-9995-3b02059ff70b.png)

### Steps to reproduce the problem

1. Open https://accounts-auth0.topcoder-dev.com/?retUrl=https://challenges.topcoder-dev.com/
2. Click Log In
3. Enter TCConnCopilot and Password
4. Click Login

### Actual behavior
- When I try to login with an existing Copilot account; I am not able to login

```
The above error occurred in the <a> component:
    in a (created by Context.Consumer)
    in Connect(a) (created by t)
    in t (created by withRouter(Connect(a)))
    in withRouter(Connect(a)) (at App.js:14)
    in t (created by t)
    in t (at App.js:13)
    in t (at App.js:12)
    in nc (at src/index.js:11)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

### Expected behavior
- Should be able to login

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.121

**Comment by sachin-maheshwari** [comment]
@codejamtc what is your handle ? looks like your account is associated with any common email.

**Comment by codejamtc** [comment]
@sachin-maheshwari I tried `TCConnCopilot` and `copilot_codejam`

**Comment by codejamtc** [comment]
@sachin-maheshwari Fixed
Please grant me permission to assign labels and edit labels

**Comment by sachin-maheshwari** [comment]
done.

**Comment by sandhiyakavi** [comment]
Verified in Prod.

![image](https://user-images.githubusercontent.com/55895538/98091638-08cf5f80-1ec9-11eb-913e-7a510757d43d.png)
