### ISSUE TITLE
WM url redirecting to old login page.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-auth-lib#45]
Description:
WM url redirecting to old login page.

![image](https://user-images.githubusercontent.com/55895538/95989414-35adcb00-0e65-11eb-878c-04afa21ee801.png)
[WM_old_login_form.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5378196/WM_old_login_form.zip)

**Comment by sachin-maheshwari** [comment]
Somebody deployed dev branch. so invalid, closing..
