### ISSUE TITLE
Getting Server Error in some pages of Direct app.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-auth-lib#46]
Description:

Getting Error in some pages of Direct app.

1. Clicking on the Project name in Dashboard page (https://www.topcoder-dev.com/direct/projectOverview?formData.projectId=7377)

<img width="960" alt="ProjectOverview_page" src="https://user-images.githubusercontent.com/55895538/96223150-6b1ef980-0fc8-11eb-965b-ef38266c7718.png">

2. Copilot Page.

<img width="960" alt="Copilotpage_504 error" src="https://user-images.githubusercontent.com/55895538/96223200-7eca6000-0fc8-11eb-939f-79347156b0e1.png">

3. Contest page

<img width="958" alt="Contestpage" src="https://user-images.githubusercontent.com/55895538/96223232-8b4eb880-0fc8-11eb-9cc2-644edb2614c5.png">

4. All challenges page

<img width="958" alt="All Challenges page" src="https://user-images.githubusercontent.com/55895538/96223263-97d31100-0fc8-11eb-9834-134a0576624a.png">

5. Profile settings page

<img width="960" alt="Profilesettingspage" src="https://user-images.githubusercontent.com/55895538/96223287-a15c7900-0fc8-11eb-9609-7ab58a61c4f6.png">

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi that is not related to "new auth flow". This could be existing issue.

**Comment by Kavi2424** [comment]
Server error occurs while creating a challenge also

![image](https://user-images.githubusercontent.com/72538736/97400223-136e7f80-1932-11eb-9661-95170353cc53.png)
