### ISSUE TITLE
Activation mail url throwing 404 Forbidden error

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-auth-lib#49]
Description:

Activation mail url throwing 404 Forbidden error.

![image (9)](https://user-images.githubusercontent.com/55895538/96417344-20052080-122c-11eb-8e4d-53d31eec8e65.png)

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi  Fixed. There was url encoding issue.

**Comment by sandhiyakavi** [comment]
Verified.Working now.
[activationurl.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5400423/activationurl.zip)

**Comment by sandhiyakavi** [comment]
Verified in Prod.
