### ISSUE TITLE
If we try to sign up via GitHub (Email already in the system); app is getting stuck 

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tc-auth-lib#50]
[2.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5400630/2.zip)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/
2. Click Sign Up
3. Click GitHub
4. Enter credentials of a GitHub (Github email is already on the system)
5. Authorize and observe

### Actual behavior
- If we try to sign up via GitHub (Email already in the system); app is getting stuck 

### Expected behavior
- Should display a proper validation

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.121

**Comment by sachin-maheshwari** [comment]
@codejamtc That is related, should be fixed with this issue. https://github.com/topcoder-platform/tc-auth-lib/issues/51

**Comment by codejamtc** [comment]
@sachin-maheshwari  I am getting below screen for already registered email (GitHub email = Already registered email) cc @SathyaJayabal 

![image](https://user-images.githubusercontent.com/42398485/96441406-1a590c00-1227-11eb-89bc-9eec6f631463.png)

When we try to register via Google account; if the email is already in the system; instead of registration, the user is logged in. I think this should happen in this scenario too?

**Comment by codejamtc** [comment]
[4.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5401316/4.zip)

**Comment by sandhiyakavi** [comment]
Verified.
