### ISSUE TITLE
If we try to sign up via GitHub (Email is not already in the system); app is getting stuck 

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tc-auth-lib#51]
[3.1.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5401018/3.1.zip)
![image](https://user-images.githubusercontent.com/42398485/96432132-15458e00-1222-11eb-9c55-963d62f6eee7.png)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/
2. Click Sign Up
3. Click GitHub
4. Enter credentials of a GitHub (Github email is not already on the system)
5. Authorize and observe

### Actual behavior
- If we try to sign up via GitHub (Email already in the system); app is getting stuck 

### Expected behavior
- Should be able to register and should receive the activation link to the email

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** FF 81.0.2

**Comment by sachin-maheshwari** [comment]
@codejamtc that was not any issue, i restricted the "private" email. now allowed, please verify now.

**Comment by SathyaJayabal** [comment]
@sachin-maheshwari , signup form github is working now.

**Comment by codejamtc** [comment]
@sachin-maheshwari  I am getting below screen for already registered email (GitHub email = Already registered email) cc @SathyaJayabal 

![image](https://user-images.githubusercontent.com/42398485/96441406-1a590c00-1227-11eb-89bc-9eec6f631463.png)

**Comment by codejamtc** [comment]
@sachin-maheshwari I am getting the registration form (Handle, First and Last name) and after registration, I can see the registration success page (https://accounts-auth0.topcoder-dev.com/register_success.html)

But I am not getting any emails @SathyaJayabal @sandhiyakavi

**Comment by sandhiyakavi** [comment]
Verified.

[github_signup_Prod.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5486629/github_signup_Prod.zip)
