### ISSUE TITLE
User is able to signup mutiple times using same email address 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/tc-auth-lib#52]
1. Create an gmail address
2. Create an account with github using the gmail address
3. Signup to topcoder using, github signup option and use the github account created in setp 2.
4. Signup to topcoder using google signup using google account created in step 1
5. Signup to topcoder using regular email address using gmail address created in step 3.

We now have three handles  using the same email address

example:
handles: `picachuigh`, `picachuigoogle`, `picachuitc` all use the same email address `picachuigh@gmail.com`

related
#37 #51 

edit: @sachin-maheshwari , the email was `topcodergh@gmail.com`

cc  @codejamtc @sandhiyakavi

**Comment by sachin-maheshwari** [comment]
@SathyaJayabal  In which bases you're saying this, i didn't find reported handled is associated with same mail..

**Comment by SathyaJayabal** [comment]
@sachin-maheshwari , can you see what emails are associated with `picachuigoogle` and `picachuitc`please?

**Comment by SathyaJayabal** [comment]
@sachin-maheshwari , for the registration through github and topcoder, I can see the same email address. For the registration through google, I dont see the handle in the db, even though I was able to sign up, using a new handle `picachuigoogle`

<img width="1440" alt="Screenshot 2020-10-19 at 5 45 28 PM" src="https://user-images.githubusercontent.com/58783823/96450212-86da0800-1233-11eb-80aa-70d5cdbd07ff.png">
<img width="1440" alt="Screenshot 2020-10-19 at 5 45 58 PM" src="https://user-images.githubusercontent.com/58783823/96450229-8ccfe900-1233-11eb-9a13-a79f683f6cf8.png">
