### ISSUE TITLE
Implement new Auth0 for submission review app

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/tc-auth-lib#57]
Implement new Auth0 for submission review app
https://submission-review.topcoder.com/

**Comment by mtwomey** [comment]
We can do this second set, but is it in your list @sachin-maheshwari ?

**Comment by sachin-maheshwari** [comment]
@SathyaJayabal / @lakshmiathreya i have deployed "new auth" related changes on DEV env. Please verify.

**Comment by sandhiyakavi** [comment]
Verified below functionalities in Dev Env. Working as expected.

1. Login
2. Token refresh
3. All page access
4. Log out

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi deployed on Prod. Please verify now.

**Comment by sandhiyakavi** [comment]
Verified below functionalities in Prod Environment. Working as expected.

Login
Token refresh
All page access
Log out

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi  Challenges link are broken for me on incognito window.
<img width="1679" alt="Screenshot 2021-01-12 at 1 13 48 PM" src="https://user-images.githubusercontent.com/6467888/104284473-13653100-54d8-11eb-8b8b-0710db660f4c.png">

<img width="1098" alt="Screenshot 2021-01-12 at 1 13 37 PM" src="https://user-images.githubusercontent.com/6467888/104284469-12340400-54d8-11eb-9248-681f4a6b8904.png">
<img width="1680" alt="Screenshot 2021-01-12 at 1 13 27 PM" src="https://user-images.githubusercontent.com/6467888/104284453-0ea07d00-54d8-11eb-94bb-8e8717630054.png">

**Comment by sandhiyakavi** [comment]
Raised new issue https://github.com/topcoder-platform/submission-review-ui/issues/31 for https://github.com/topcoder-platform/tc-auth-lib/issues/57#issuecomment-758471930
