### ISSUE TITLE
Does not open login window for Lauscher app in safari

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/tc-auth-lib#58]
Test URL : https://lauscher.topcoder-dev.com/
Browser : Safari

Reference 
https://snipboard.io/CVR21B.jpg

**Comment by sachin-maheshwari** [comment]
Looks like it Safari specific issue. So to avoid confusion (if retUrl is missing) i added an alert message. @drasticdpk please try one more time and lets if issue is due to missing retUrl ? 
<img width="1351" alt="Screenshot 2020-10-20 at 5 02 01 PM" src="https://user-images.githubusercontent.com/6467888/96580758-658e2000-12f6-11eb-95c4-62a038f24bec.png">

**Comment by drasticdpk** [comment]
@sachin-maheshwari , Now we can get alert message, but the issue has not fixed yet, right ? 
now we can get 
Reference :
![image](https://user-images.githubusercontent.com/25297859/96679237-fca8b580-1392-11eb-85d9-9afc666e28d6.png)

**Comment by drasticdpk** [comment]
Update : We got the same issue on
 https://payment.topcoder-dev.com/

**Comment by sachin-maheshwari** [comment]
@drasticdpk / @lakshmiathreya "https://lauscher.topcoder-dev.com/" is working fine for me on Safari browser. Please verify and close the issue.

**Comment by drasticdpk** [comment]
@sachin-maheshwari ,
For lausher app, we don't have login window ? 
![image](https://user-images.githubusercontent.com/25297859/103894155-9a9c5880-5116-11eb-84e8-5651b5ef1e2c.png)

I am having this window while hitting the given url https://lauscher.topcoder-dev.com/. Correct me if I am getting worng.

![image](https://user-images.githubusercontent.com/25297859/103894219-b43da000-5116-11eb-93c9-bb90819d734e.png)

**Comment by sachin-maheshwari** [comment]
@drasticdpk which Safari version and which OS, you are facing this issue ? For me, on MAC its working fine for me.  
<img width="1327" alt="Screenshot 2021-01-07 at 6 32 07 PM" src="https://user-images.githubusercontent.com/6467888/103895604-a9830b00-5116-11eb-8c3a-bdd5aa934884.png">

**Comment by sachin-maheshwari** [comment]
@lakshmiathreya please get it verify from your team.

**Comment by drasticdpk** [comment]
@sachin-maheshwari , 
FYI
![image](https://user-images.githubusercontent.com/25297859/104622645-a0b3ab80-56b9-11eb-8c87-f15e43fe16bb.png)

**Comment by drasticdpk** [comment]
Now it is working as expected, so closing it.  cc @lakshmiathreya 
Reference : 
![image](https://user-images.githubusercontent.com/25297859/124266401-a82b1c00-db56-11eb-8e27-568fb784c9e6.png)
