### ISSUE TITLE
Display message to user to clear cookies and login again after auth0 release

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/tc-auth-lib#59]
1. User is logged in through accounts app (old app) in community app
2. Release of auth0 for comm app
3. User accesses Comm app pages

Expected: Display a message instructing the user to clear their cookies and then login again. 
Actual: Blank page is displayed.

**Comment by vikasrohit** [comment]
Can we not send response headers to clear all cookies of our domain when user clicks on logout?

**Comment by sachin-maheshwari** [comment]
@SathyaJayabal i tried as @vikasrohit suggested to clean old cookies. Now its working at my end. Can you please verify quickly without incognito ?

**Comment by SathyaJayabal** [comment]
@sachin-maheshwari , verified on safari and chrome. Looks good.
User is able to access and use app even when logged in from old accounts app. They are able to logout and then login using new auth0.
