### ISSUE TITLE
Registered  Country is not reflecting on Profile Setting page.

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/tc-auth-lib#6]
**Steps** :
1. Go to https://qa-community-app.topcoder-dev.com/members/TonyJ
2. Click Login button.
3. Go to sign up section 
4. Fill the data, submit the form and observe the email

**Expected** : 
Registered country should reflect on profile setting page.

**Reference** 
 
![image](https://user-images.githubusercontent.com/25297859/92605335-549ec780-f2d1-11ea-80a6-2ccf9add9550.png)

Note : This is existing issue, if possible please solve it.

**Comment by sachin-maheshwari** [comment]
Not sure if it is existing issue. As i tried and check at database. It is there. 

select * from informixoltp.coder order by coder_id = '88774205' ;

**Comment by sachin-maheshwari** [comment]
@drasticdpk looks like existing issue.
