### ISSUE TITLE
Unable to logout from the system. 

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/tc-auth-lib#60]
Test UrL. : https://accounts-auth0.topcoder.com/?retUrl=https://apps.topcoder.com/forums/ 
Browser : All
Reference : https://snipboard.io/BvEshm.jpg

**Comment by sachin-maheshwari** [comment]
@drasticdpk We have not deployed fully on Prod. so this invalid until we deploy fully (all essential services and components).
