### ISSUE TITLE
Staging Env: Logout of Community app not working

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-auth-lib#62]
Description:

 Logout of Community app not working

[Community_logout_fail.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5408233/Community_logout_fail.zip)

https://staging-community-app.topcoder.com/challenges

**Comment by SathyaJayabal** [comment]
On firefox.
<img width="1440" alt="Screenshot 2020-10-20 at 4 46 06 PM" src="https://user-images.githubusercontent.com/58783823/96579031-c9631980-12f3-11eb-8f92-d03ab6116718.png">

**Comment by sachin-maheshwari** [comment]
<img width="1680" alt="Screenshot 2020-10-22 at 8 05 58 PM" src="https://user-images.githubusercontent.com/6467888/96887307-184eb180-14a2-11eb-96e0-378071b7e925.png">
Once we deploy the docker-supply on production it will be fixed.

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi please verify and close this.

**Comment by sandhiyakavi** [comment]
Verified in Prod. Working as expected.
[Communityapp_logout.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5713670/Communityapp_logout.zip)
