### ISSUE TITLE
Dev Env: Topgear SSO new user unable to register 

### ISSUE THREAD

**Issue by lakshmiathreya** [topcoder-platform/tc-auth-lib#63]
-- In order to simulate a new SSO user scenario for Topgear - Changed my existing SSO email to 'lakshmi.athreya+ssotest@gmail.com' to make sure it doesn't match with my SSO user 'lakshmi.athreya@topcoder.com'. 
-- Removed this user from Wipro-all.
-- Logged into https://topgear.topcoder-dev.com - taken to Wipro adfs login as expected.
-- Upon logging into Wipro with my adfs credentials la20087117@wipro.com - next - a Registration success screen is seen.
-- However, no activation email is sent to lakshmi.athreya+ssotest@gmail.com
<img width="1578" alt="Screenshot 2020-10-20 at 6 57 38 PM" src="https://user-images.githubusercontent.com/51733042/96592839-734ba180-1306-11eb-8d0a-e2894d2e3806.png">
<img width="1629" alt="Screenshot 2020-10-20 at 6 58 04 PM" src="https://user-images.githubusercontent.com/51733042/96592859-7a72af80-1306-11eb-9f4e-1dd2e2314096.png">

**Comment by sachin-maheshwari** [comment]
@lakshmiathreya for enterprise customer there is no need of activation email. So looks like invalid issue.

**Comment by mtwomey** [comment]
Agree email is not intended to be sent for enterprise account, should this one close?

**Comment by sachin-maheshwari** [comment]
@lakshmiathreya should be fixed now. correct ?

**Comment by lakshmiathreya** [comment]
New User registration successful for Topgear. However, in the Join Topcoder form - I chose "lakshmiwipro" as my handle - I see handle as "lakshmi.athreya" here: Pls clarify @sachin-maheshwari 
<img width="1655" alt="Screenshot 2020-10-22 at 8 53 08 PM" src="https://user-images.githubusercontent.com/51733042/96893768-af1e6c80-14a8-11eb-879d-53440c022c49.png">

**Comment by lakshmiathreya** [comment]
If account name is the default handle being pre-selected for a new Enterprise user - then the handle field in the Join Topcoder form may be unnecessary.
