### ISSUE TITLE
Google signup not taking the Username provided by the user.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-auth-lib#66]
Description:

Google signup not taking the username provided by the user.

Actual Result:

It is taking user name from the mail id provided 

Example: If Email id: sampleid@gmail.com .It is taking user handle as sampleid irrespective of the one provided by the user.

![image](https://user-images.githubusercontent.com/55895538/96839284-ed556500-1483-11eb-9933-6662aaf10736.png)

![image](https://user-images.githubusercontent.com/55895538/96839465-34435a80-1484-11eb-97ef-c42bdec8364a.png)

[Google_signup.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5420903/Google_signup.zip)

**Comment by sdgun** [comment]
Verified, this issue is not still fixed.

![image](https://user-images.githubusercontent.com/4592712/97262618-3e2fd980-1847-11eb-9c34-bd3c96e52e21.png)

![image](https://user-images.githubusercontent.com/4592712/97262630-45ef7e00-1847-11eb-8fb2-5f16485f96e9.png)

**Comment by nkumar-topcoder** [comment]
@sdgun   can you please retest this and get back. It should be "account" screen not "basic info"

**Comment by SathyaJayabal** [comment]
@nkumar-topcoder @sachin-maheshwari , looks to be fixed now.
<img width="1440" alt="Screenshot 2020-10-27 at 4 28 47 PM" src="https://user-images.githubusercontent.com/58783823/97292661-8b28a580-1871-11eb-9d92-fbf18d32c3d8.png">

**Comment by sandhiyakavi** [comment]
Verified.

[google_signup_Prod.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5486816/google_signup_Prod.zip)
