### ISSUE TITLE
Activation mail's return URL issues

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-auth-lib#67]
Description:

Activation mail return url for Community app is different for Google and Direct signup.

Google Signup -> Getting Start page
Direct Signup -> Getting Community app's challenge listing page.

![image](https://user-images.githubusercontent.com/55895538/96840925-1119aa80-1486-11eb-9cc8-c6646349c39f.png)

![image](https://user-images.githubusercontent.com/55895538/96841012-2a225b80-1486-11eb-8e24-9063c0d30737.png)

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi lets cover all scenarios like from connect-app and "join topcoder" from footer and if you at any challenge detail and login (new registration).

**Comment by sandhiyakavi** [comment]
@sachin-maheshwari I have added all the expected return url's (Current behaviour) in this sheet https://drive.google.com/file/d/19FHrkfNWF4GlV4a9NKglp4T5ZdWYSttC/view?usp=sharing 

Please review and let me know for any clarification.

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi should be fixed now. Please verify and close.

**Comment by sandhiyakavi** [comment]
Verified in Prod. Working as expected.
