### ISSUE TITLE
Activation mail not received for GitHub signup

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-auth-lib#68]
Description:

Activation mail not received for GitHub signup

[github_signup.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5421311/github_signup.zip)

**Comment by sandhiyakavi** [comment]
Verified .GitHub signup is working now.

[GitHub_signup_Pass.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5436923/GitHub_signup_Pass.zip)

**Comment by sdgun** [comment]
@sachin-maheshwari I tried the Github sign up in Android and it is still not sending the activation email. 
Github account used - sdguntcqagithub@gmail.com 
Topcoder user name - sdguntcqagh1

Note- Tried activating account by accessing Github from Log in page

**Comment by sandhiyakavi** [comment]
Verified in Prod.
