### ISSUE TITLE
Google sign in requests for MFA on prod

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/tc-auth-lib#69]
Google sign in requests for MFA on prod.
<img width="1440" alt="Screenshot 2020-10-22 at 3 11 18 PM" src="https://user-images.githubusercontent.com/58783823/96861822-458b6780-1482-11eb-8039-880e92ddee51.png">

@sachin-maheshwari , This was working fine few hours back.

**Comment by SathyaJayabal** [comment]
verified on prod(staging)

**Comment by sachin-maheshwari** [comment]
Anyway it is not related to our "new auth" changes. Support team enabled MFA at Auth0 by mistake.

**Comment by SathyaJayabal** [comment]
@sachin-maheshwari , closing this issue as its not related to auth0
