### ISSUE TITLE
Unable to logout from system.

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/tc-auth-lib#7]
**Steps** :
1. Go to https://qa-community-app.topcoder-dev.com/members/TonyJ
2. Click Login button.
3. login with valid credential.
4. Try to logout from the system.
5. Go to https://qa-community-app.topcoder-dev.com/members/TonyJ

**Expected** : 
User should log out from system.

**Reference** 
 
![image](https://user-images.githubusercontent.com/25297859/92606312-85cbc780-f2d2-11ea-8522-084aa2a88131.png)

Note : This is existing issue, if possible please solve it.

**Comment by sachin-maheshwari** [comment]
I am planning to handle it through one place (i.e. nginx) and after logout from any application it will land to our website (topcoder.com) only.

**Comment by sandhiyakavi** [comment]
Verified. Logout is working now.

[Logout_functionaity.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5311180/Logout_functionaity.zip)
