### ISSUE TITLE
Google login in Mobile device fails

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-auth-lib#71]
Description:

Google account login in mobile device is failing. Getting below screen

<img width="275" alt="Mobile_Google_login" src="https://user-images.githubusercontent.com/55895538/96998286-2833c780-156e-11eb-8a71-77ea18cd80a9.png">

Device information:

Phone : iPhone 7
Version: 12.2
Browser: Chrome

**Comment by sdgun** [comment]
Verified in IOS and Android, Google account login is successful.

Phone : iPhone 6S
Version: 13.4
Browser: Chrome

Phone : Andriod Google Pixel XL
Version: 10
Browser: Chrome

**Comment by sandhiyakavi** [comment]
Verified in Prod.
