### ISSUE TITLE
User has to scroll down to see the log in button in Android

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-auth-lib#73]
**Steps**
Go to https://staging-community-app.topcoder.com/challenges
Click LOGIN 

The Log In UI is loaded but the Log In button is far below, the User has to scroll down to see it

![image](https://user-images.githubusercontent.com/4592712/97139955-b16f1800-1781-11eb-8a55-0957237ad042.png)

**Comment by nkumar-topcoder** [comment]
@sdgun This is not an issue, the scope is "new auth" testing only, The UI design is preexisting and not part of the scope. 
FYI @lakshmiathreya @sachin-maheshwari

**Comment by drasticdpk** [comment]
Now it is working as expected, so closing it. If anything we can open it.
