### ISSUE TITLE
Token Refresh is not working in FF for Auth0 - Set-2

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tc-auth-lib#76]
![image](https://user-images.githubusercontent.com/42398485/97170543-e1ceaa80-17b1-11eb-9d4e-c7cf62523fd8.png)

1. Login to the app ([Payment](https://payment.topcoder-dev.com/), [Topcoder X](https://x.topcoder-dev.com/) 
2. Check the token; after 10-15mins
3. Still the old token displayed

**Comment by sachin-maheshwari** [comment]
@codejamtc On other browser, are these working ?

**Comment by sachin-maheshwari** [comment]
<img width="1680" alt="Screenshot 2020-10-26 at 6 30 27 PM" src="https://user-images.githubusercontent.com/6467888/97175402-7688d680-17b9-11eb-8817-2c54b1be9371.png">
I checked randomly Vanilla Forum, token is refreshing from me on DEV for Chrome browser.

**Comment by codejamtc** [comment]
@sachin-maheshwari I checked Edge, it is working properly. FF it is not

**Comment by codejamtc** [comment]
@sachin-maheshwari I checked again, for [Forums ](https://vanilla.topcoder-dev.com/)- It's working now

**Comment by sachin-maheshwari** [comment]
@codejamtc so finally what is not working on which browser ?

**Comment by codejamtc** [comment]
@sachin-maheshwari You can ignore this ticket; Chrome, Firefox, Edge - All working

**Comment by codejamtc** [comment]
@sachin-maheshwari This is applicable for Payment, Topcoder X for Firefox browser
