### ISSUE TITLE
X.Topcoder : Unable to open in Safari browser.

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/tc-auth-lib#77]
**Test URL** :  https://x.topcoder-dev.com/
**Browser** : Safari
**Reference** : https://snipboard.io/CRlgnu.jpg

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2020-10-27 at 10 22 22 AM" src="https://user-images.githubusercontent.com/58783823/97258419-623aed00-183e-11eb-845c-46ee2f3b3f89.png">
<img width="1440" alt="Screenshot 2020-10-27 at 10 22 38 AM" src="https://user-images.githubusercontent.com/58783823/97258520-91e9f500-183e-11eb-8adc-c61b2dfe9aea.png">

**Comment by sachin-maheshwari** [comment]
@drasticdpk / @lakshmiathreya its opening for me on Safari. Please re-verify and close this.

**Comment by SathyaJayabal** [comment]
@sachin-maheshwari , this is already verified on dev. I dont see new auth0 on prod yet. Is it released for topcoder-x app yet?

we usually close the issue after verification on prod.

**Comment by sachin-maheshwari** [comment]
FYI, 
<img width="655" alt="Screenshot 2021-01-07 at 6 49 08 PM" src="https://user-images.githubusercontent.com/6467888/103897148-18f9fa00-5119-11eb-91c8-2b5db867b2e9.png">

**Comment by drasticdpk** [comment]
Verified 
dev 

![image](https://user-images.githubusercontent.com/25297859/104302309-b7f36d00-54f0-11eb-963b-c5fae065d87e.png)

prod 
![image](https://user-images.githubusercontent.com/25297859/104301883-40254280-54f0-11eb-88ec-9328f1f53b69.png)
