### ISSUE TITLE
Payment app: login not working for safari browser

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/tc-auth-lib#79]
https://payment.topcoder-dev.com/
login not working for safari browser
<img width="1440" alt="Screenshot 2020-10-27 at 11 22 31 AM" src="https://user-images.githubusercontent.com/58783823/97262490-f1e49980-1846-11eb-81ac-c3f16849e03e.png">

**Comment by sachin-maheshwari** [comment]
@SathyaJayabal / @lakshmiathreya Login popup is opening for me on Safari. Please verify and close it.

**Comment by SathyaJayabal** [comment]
@sachin-maheshwari , login is opening in dev.  Is auth0 not yet released for payments app  in prod?

<img width="1440" alt="Screenshot 2021-01-07 at 6 32 02 PM" src="https://user-images.githubusercontent.com/58783823/103895598-a8ea7480-5116-11eb-8e31-39b51e26c59f.png">

**Comment by sachin-maheshwari** [comment]
@SathyaJayabal i am not sure. I asked same question on "product-team-chatter". Looks like we are not using actively. Let's wait for final response. 
<img width="1392" alt="Screenshot 2021-01-07 at 6 39 31 PM" src="https://user-images.githubusercontent.com/6467888/103896352-d97ede00-5117-11eb-9e76-2a6866e640b7.png">

**Comment by sachin-maheshwari** [comment]
FYI,
<img width="405" alt="Screenshot 2021-01-07 at 6 53 20 PM" src="https://user-images.githubusercontent.com/6467888/103897495-ab9a9900-5119-11eb-9711-d987db11705c.png">

**Comment by SathyaJayabal** [comment]
Closing the issue in that case @sachin-maheshwari
