### ISSUE TITLE
Can we have login function in  modal dialog instead of web browser ?

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/tc-auth-lib#8]
**Steps** :
 Go to https://accounts-auth0.topcoder-dev.com/?retUrl=https%3A%2F%2Ftopcoder-dev.com%2Fdirect%2F

**Problem** 
Currently login window goes to background (as different browser tab) if user click out side the login section. As user some time It will confuse there is login window available or not.

**Suggestion **
Login window should open in modal dialog box instead of browser.

**Reference** 
 
![image](https://user-images.githubusercontent.com/25297859/92716296-5d010c00-f37e-11ea-87f5-1737e9087231.png)

**Comment by sandhiyakavi** [comment]
@sachin-maheshwari Login window opening as pop up now. But there are cosmetic errors in the display of Error messages.

1. Error messages are not displaying in single line.
2. Half of the message is not displayed for some error messages. 

<img width="938" alt="Screenshot_4" src="https://user-images.githubusercontent.com/55895538/94399277-0a0ebd80-01a2-11eb-97cd-2147819bd931.png">

**Comment by sandhiyakavi** [comment]
closing the issue as the cosmetic issue is tracked separately in issue https://github.com/topcoder-platform/tc-auth-lib/issues/40
