### ISSUE TITLE
Register via Social login (Google) will display a different handle after login

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tc-auth-lib#82]
![image](https://user-images.githubusercontent.com/42398485/97396308-cf1cb880-190c-11eb-86ee-8af2b48447b1.png)

### Steps to reproduce the problem

1. Open https://connect-auth0.topcoder.com
2. Click Login
3. Click Sign up > Google Social Login and login as the Google account
4. Enter handle as `codejamtcqag1` and enter the country
5. Register
6. Now Login using the Google account

Don't know whether this is because we are using the accounts again and again after clean-up. But this should not happen even after cleaning the accounts from the db

### Actual behavior
- Register via Social login (Google) will display a different handle after login

### Expected behavior
- Should display the entered login while registering

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome  86.0.4240.111

**Comment by SathyaJayabal** [comment]
@codejamtc , is the handle displayed the first part of the google mail address (example : `username` of `username@gmail.com` ?

**Comment by codejamtc** [comment]
@SathyaJayabal Yes

**Comment by SathyaJayabal** [comment]
related https://github.com/topcoder-platform/tc-auth-lib/issues/66
happened in comm app too, but fixed now

**Comment by lakshmiathreya** [comment]
Handle selected by user during Registration is not used to set User Handle. Account name seems to be used for Handle creation: 
<img width="1330" alt="Screenshot 2020-10-30 at 8 53 12 PM" src="https://user-images.githubusercontent.com/51733042/97725151-d8b44500-1af3-11eb-947e-37fad4508ac6.png">
<img width="1335" alt="Screenshot 2020-10-30 at 8 54 01 PM" src="https://user-images.githubusercontent.com/51733042/97725190-e669ca80-1af3-11eb-9564-4035f260f88c.png">

**Comment by sachin-maheshwari** [comment]
@codejamtc can you please verify now.

**Comment by sachin-maheshwari** [comment]
@lakshmiathreya please get this verified from your team.

**Comment by sachin-maheshwari** [comment]
no response.
