### ISSUE TITLE
Not able to login to scorecard/Direct app after Password changed using the scorecard/Direct app

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-auth-lib#83]
Description:

Not able to login to scorecard app after Password changed using the scorecard app. Getting Flickering image (unstable page).

Steps to Reproduce:

1. Reset password from the Scorecard app (https://www.topcoder-dev.com/scorecard)
2. Try to login from the scorecard app with the changed password.

Expected result:
User should be able to login successfully .

Actual result:
Getting flickering image (unstable page) and not logging in the app.

![image](https://user-images.githubusercontent.com/55895538/97413955-bcbf7080-1946-11eb-9a7d-0a642db5e899.png)
[passwordreset_scorecard.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5450667/passwordreset_scorecard.zip)

**Comment by sandhiyakavi** [comment]
Similar issue is happening for Direct app

**Comment by sachin-maheshwari** [comment]
looking similer issue - https://github.com/topcoder-platform/tc-auth-lib/issues/86
