### ISSUE TITLE
Click on the activation link from the email redirect the page to start page

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tc-auth-lib#84]
![image](https://user-images.githubusercontent.com/42398485/97547885-601a8f00-19f4-11eb-8a37-e57498a8f490.png)

### Steps to reproduce the problem

1. Open connect.topcoder-dev.com
2. Click Login
3. Click Sign up > Google Social Login and login as the Google account
4. Enter Handle as `codejamtcqag1` and enter the country
5. Register
6. Click on the activation link (http://link.topcoder.com/ls/click?upn=d5dokG-2BeRN5T9sXjloHtOWSDH-2FI6Vm9amva3NRvNNFRJPrGX8e2SclkmaVmjMrTqYhAEz0mupRJqy1QfM3D9KxXrr0Gt-2B3sprHznK-2B7KFYV6nDcXfg-2BtszRPKTrq0NFTBQ90qpHxTmLF-2F5nTgllkMOkuCNOX0yb-2F4LOxf3Oebk0-3DfD37_fOcGOHx1LBhx-2FfhMQ-2Bid9s5XKtRASMNLpyPzzh5-2F3T8cFTq-2B6Nm5vIkIFv3MBuvv-2FBRwgpNpH-2BBYiYdGX2h1xiklMnayql49dulNEg5wP-2FjX64TeiW2I66Iy2iBsqLuKfTbxWa5MgnGa9PYOUtMxpZbLHwjLVW-2FjpHeMv7ugvZUe01KXxQpH4k1OYeg41vhrxLR-2FqiyQk2vI7Hc8c6AQZfsRiQHg6FUGjSBBp426tP-2BfPXaX3KBhmdB7-2Bdos217IDhAwyxyZ7uVyvSZRD0tdOA-3D-3D)

### Actual behavior
- Click on the activation link from the email redirect the page to start page

### Expected behavior
- Should display redirect the page to connect home page

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome  86.0.4240.111

**Comment by sachin-maheshwari** [comment]
@codejamtc should be fixed now. Please verify and close this.

**Comment by sachin-maheshwari** [comment]
@lakshmiathreya no response from your team.
