### ISSUE TITLE
Token Refresh is not working for dev Direct app

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/tc-auth-lib#85]
**Steps** 
1. Log on to direct app with valid credentials. 
  >  https://www.topcoder-dev.com/direct
2. Wait for 10 min and reload the page. 

**Reference** : 
https://snipboard.io/kDK2Cc.jpg

**Comment by sachin-maheshwari** [comment]
@drasticdpk should be fixed now. Please verify and close this.
