### ISSUE TITLE
Logout form forums not working

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/tc-auth-lib#87]
Need to update logout link from forums
<img width="1440" alt="Screenshot 2020-10-29 at 10 46 37 PM" src="https://user-images.githubusercontent.com/58783823/97608670-a691dd00-1a38-11eb-9b25-9fe895626adc.png">

**Comment by sachin-maheshwari** [comment]
@mtwomey FYI, looks like we need to change in coressponsig file manually - https://apps.topcoder.com/js/reskin/newTCScript.js at doLogOutTC() function.

**Comment by sachin-maheshwari** [comment]
@ajefts we are planning to change manually in this file, we didn't the git repo for same. 
File location is -  /mnt/nginx/apache_docs/tcdocs/js/reskin
Server - nginx-supply

**Comment by sachin-maheshwari** [comment]
Fixed. @SathyaJayabal please verify and close this issue.

**Comment by sandhiyakavi** [comment]
Verified in Prod. Able to logout.
[OldForum_logout.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5713684/OldForum_logout.zip)
