### ISSUE TITLE
Error on Password reset

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/tc-auth-lib#92]
When user enters new password to reset their password, the following error is displayed. The new password is reset successfully though.
![image (13)](https://user-images.githubusercontent.com/58783823/97707475-5ae53f00-1add-11eb-9d3d-e50074f557c1.png)

**Comment by sachin-maheshwari** [comment]
@SathyaJayabal please close, should be fixed now.

**Comment by sandhiyakavi** [comment]
Verified working as expected.

![image](https://user-images.githubusercontent.com/55895538/102038912-d3912800-3e0b-11eb-96f6-a007b2a2b759.png)
