### ISSUE TITLE
Infinite loop during local deployment of Connect App, Work Manager and Community App

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-auth-lib#98]
Looks like since today this library causes an infinite loop of errors when deploying any client app utilizing this library locally like Connect App, Work Manager, or Community App.

See demo videos:
- Connect App https://monosnap.com/file/p6YodFZESEy7HIvpyziBHNU6fQNaZo
- Work Manager https://monosnap.com/file/sooQ9gXaUrilN8EUh3xgCRYO90Mq5H
- Community App https://monosnap.com/file/rnl8L1cqwA3JVMpKQwLVpIfWzvJYDn

This loop heavily loads the CPU and makes the local work not comfortable:

![image](https://user-images.githubusercontent.com/146016/99675090-752c9000-2a7f-11eb-9850-da04c8fcab92.png)

This is caused by this error https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-auth0-spa-js-must-run-on-a-secure-origin.

Which requires us to use one of the next domains:

```
(https, *, *)
(wss, *, *)
(*, localhost, *)
(*, 127/8, *)
(*, ::1/128, *)
(file, *, —)
```

Locally we are using domain `http://local.topcoder-dev.com` or `http://local.topcoder.com` which don't match these patterns.

- We cannot use the domain `localhost` because auth library doesn't allow it.
- It also hard to configure `https` domain locally for `local.topcoder-dev.com` because of Chromium browsers blocking the certificate created by Webpack Development Server.

So it would be great if we can catch this error in `tc-auth-lib` so to avoid an infinite loop.

**Comment by sachin-maheshwari** [comment]
@maxceem i am attaching code to generate token locally. Please try this in separate tab and use your app on localhost:3000. 
[test-app-locally.zip](https://github.com/topcoder-platform/tc-auth-lib/files/5571374/test-app-locally.zip)

**Comment by maxceem** [comment]
Thanks, @sachin-maheshwari.

This worked for me. So I login using your test app, and after I can use Connect App, though I cannot login using Connect App on `http://localhost:3000` in some reason.

Btw, when I login in the test app, one request fails even after I login, is that expected behavior? See [demo video](https://monosnap.com/file/n63vdPjJsKsBrqFn8xfi6LUzFKoUiJ) and screenshot below.

![image](https://user-images.githubusercontent.com/146016/99776555-ae194300-2b19-11eb-9d91-b0a8b3125816.png)

**Comment by maxceem** [comment]
Noticed one more thing. After I login using the provided test app, I can open Connect App on `http://localhost:3000` and it works well. But Connect App cannot refresh the token. So after 5 minutes token expires, and I have to clear cookies, stop Connect App and login again using test app.

**Comment by sachin-maheshwari** [comment]
@maxceem just keep open test app in separate tab. It'll take care of token expiry, also you can download latest code for test app from here - https://github.com/topcoder-platform/tc-auth-lib/blob/dev/web-assets/js/setupAuth0WithRedirect.js

**Comment by maxceem** [comment]
@sachin-maheshwari this way with the test app opened in another tab works for me. 

Would it be also possible to run apps like Connect App and Community App independently? I've tried to run them on `localhost:3000` or `localhost:5000` but they cannot login by themself. Should we make any changes to them?

**Comment by sachin-maheshwari** [comment]
@maxceem I didn't get fully, i think its simply depending on local setup and application port. I think, in that case you need to change the ACCOUNT_APP url to localhost ?

**Comment by maxceem** [comment]
@sachin-maheshwari my intention is to run the Connect App locally without running `test-app-locally.zip` app. I'm trying to run Connect App on port `localhost:5000` but login doesn't work. I've recorded a demo video to demonstrate the issue: https://monosnap.com/file/fo6Ga7dAtIG63w5xXviHiH7JRctIeG

What I do:
- Run Connect App locally on the allowed port `5000` using URL `http://localhost:5000` (I use `dev` branch, the latest commit `5be8d079e9308a659678f7ea9c62ca1764a45294`)
- Open `http://localhost:5000` in **Incognito Mode**
- Click **Login** and fill username and password
- I get redirected back to `http://localhost:5000` but login didn't work. Even though I can see the JWT token in the console log, but there is some error, maybe it's the reason, but I don't know:

    ![image](https://user-images.githubusercontent.com/146016/100210459-b1467180-2f13-11eb-8a61-e40f34078dfa.png)

I'm not sure where is the issue here. Should we update Connect App somehow so it can be run locally with the new login process? Or should `tc-auth-lib` be changed somehow?

**Comment by sachin-maheshwari** [comment]
@maxceem just changes "accounts-auth0.topcoder-dev.com" value to your test app URL i.e. http://localhost:5000 and you will be able to use connect-app locally and token will be refreshed. 
<img width="1309" alt="Screenshot 2020-11-25 at 6 04 29 PM" src="https://user-images.githubusercontent.com/6467888/100228426-ace87b80-2f48-11eb-9912-7d00f626c152.png">

<img width="1638" alt="Screenshot 2020-11-25 at 5 58 48 PM" src="https://user-images.githubusercontent.com/6467888/100228181-4e230200-2f48-11eb-8346-f4f85a4649bd.png">
<img width="1676" alt="Screenshot 2020-11-25 at 6 01 29 PM" src="https://user-images.githubusercontent.com/6467888/100228193-52e7b600-2f48-11eb-9085-8e5ca310cb35.png">

**Comment by maxceem** [comment]
@sachin-maheshwari thanks, I got it now.

Though I wonder, is it possible to run `Connect App`, `Community App`, `Admin App`, `Work Manager App` locally without the necessity of running `test-app-locally.zip` locally? As it adds one more step for local deployment.

**Comment by sachin-maheshwari** [comment]
For now, no.

**Comment by maxceem** [comment]
Got it, thanks!

As I understand `logging-out` is not supported locally for now too. Even when using `test-app-locally.zip` locally, right? For now, it looks like his to me, when I'm trying to logout https://monosnap.com/file/esM8beLw4NZud0ONst1PU2nNtCjiTU.

**Comment by sachin-maheshwari** [comment]
I'll check this. 

Meanwhile you can use this to logout - http://localhost:5000/?logout=true&retUrl=http://localhost:3000/

**Comment by maxceem** [comment]
Thanks, @sachin-maheshwari. Your URL works for me, I've updated it in the app, so logging out now works for me.
